// data.js
const hsk1_vocab_full = [
  {
    id: 1,
    hanzi: "爱",
    pinyin: "ài",
    meaning_vi: "Yêu, thích",
    example: "我爱学习汉语 (Wǒ ài xuéxí Hànyǔ) - Tôi yêu học tiếng Trung.",
  },
  {
    id: 2,
    hanzi: "八",
    pinyin: "bā",
    meaning_vi: "số 8",
    example: "他八岁了 (Tā bā suì le) - Nó 8 tuổi rồi.",
  },
  {
    id: 3,
    hanzi: "爸爸",
    pinyin: "bàba",
    meaning_vi: "bố, ba",
    example: "我爸爸是老师 (Wǒ bàba shì lǎoshī) - Bố tôi là giáo viên.",
  },
  {
    id: 4,
    hanzi: "杯子",
    pinyin: "bēizi",
    meaning_vi: "cái cốc, cái ly",
    example:
      "桌子上有一个杯子 (Zhuōzi shàng yǒu yí gè bēizi) - Trên bàn có một cái cốc.",
  },
  {
    id: 5,
    hanzi: "北京",
    pinyin: "Běijīng",
    meaning_vi: "Bắc Kinh",
    example: "我去过北京 (Wǒ qùguo Běijīng) - Tôi từng đi Bắc Kinh.",
  },
  {
    id: 6,
    hanzi: "本",
    pinyin: "běn",
    meaning_vi: "quyển, cuốn",
    example: "这本书很好看 (Zhè běn shū hěn hǎokàn) - Quyển sách này rất hay.",
  },
  {
    id: 7,
    hanzi: "不",
    pinyin: "bù",
    meaning_vi: "không",
    example: "我不去学校 (Wǒ bú qù xuéxiào) - Tôi không đi đến trường.",
  },
  {
    id: 8,
    hanzi: "不客气",
    pinyin: "búkèqi",
    meaning_vi: "đừng khách sáo",
    example: "谢谢你！不客气 (Xièxie nǐ! Búkèqi) - Cảm ơn bạn! Đừng khách sáo.",
  },
  {
    id: 9,
    hanzi: "菜",
    pinyin: "cài",
    meaning_vi: "rau, món ăn",
    example:
      "中国菜很好吃 (Zhōngguó cài hěn hǎochī) - Món ăn Trung Quốc rất ngon.",
  },
  {
    id: 10,
    hanzi: "茶",
    pinyin: "chá",
    meaning_vi: "trà",
    example: "请喝茶 (Qǐng hē chá) - Mời uống trà.",
  },
  {
    id: 11,
    hanzi: "吃",
    pinyin: "chī",
    meaning_vi: "ăn",
    example: "吃米饭 (chī mǐfàn) - Ăn cơm.",
  },
  {
    id: 12,
    hanzi: "出租车",
    pinyin: "chūzūchē",
    meaning_vi: "xe taxi",
    example: "坐出租车去 (zuò chūzūchē qù) - Đi bằng xe taxi.",
  },
  {
    id: 13,
    hanzi: "打电话",
    pinyin: "dǎ diànhuà",
    meaning_vi: "gọi điện thoại",
    example: "他在打电话 (Tā zài dǎ diànhuà) - Anh ấy đang gọi điện thoại.",
  },
  {
    id: 14,
    hanzi: "大",
    pinyin: "dà",
    meaning_vi: "to, lớn",
    example: "这个苹果很大 (Zhège píngguǒ hěn dà) - Quả táo này rất lớn.",
  },
  {
    id: 15,
    hanzi: "的",
    pinyin: "de",
    meaning_vi: "của (trợ từ)",
    example: "这是我的书 (Zhè shì wǒ de shū) - Đây là sách của tôi.",
  },
  {
    id: 16,
    hanzi: "点",
    pinyin: "diǎn",
    meaning_vi: "giờ, chút ít",
    example: "现在三点 (Xiànzài sān diǎn) - Bây giờ là 3 giờ.",
  },
  {
    id: 17,
    hanzi: "电脑",
    pinyin: "diànnǎo",
    meaning_vi: "máy tính",
    example: "买电脑 (mǎi diànnǎo) - Mua máy tính.",
  },
  {
    id: 18,
    hanzi: "电视",
    pinyin: "diànshì",
    meaning_vi: "ti vi",
    example: "看电视 (kàn diànshì) - Xem ti vi.",
  },
  {
    id: 19,
    hanzi: "电影",
    pinyin: "diànyǐng",
    meaning_vi: "phim",
    example: "看电影 (kàn diànyǐng) - Xem phim.",
  },
  {
    id: 20,
    hanzi: "东西",
    pinyin: "dōngxi",
    meaning_vi: "đồ vật",
    example: "买东西 (mǎi dōngxi) - Mua đồ.",
  },
  {
    id: 21,
    hanzi: "都",
    pinyin: "dōu",
    meaning_vi: "đều",
    example:
      "我们 đều là bạn (Wǒmen dōu shì péngyou) - Chúng tôi đều là bạn bè.",
  },
  {
    id: 22,
    hanzi: "读",
    pinyin: "dú",
    meaning_vi: "đọc",
    example: "读课文 (dú kèwén) - Đọc bài khóa.",
  },
  {
    id: 23,
    hanzi: "对不起",
    pinyin: "duìbuqǐ",
    meaning_vi: "xin lỗi",
    example:
      "对不起，我迟到了 (Duìbuqǐ, wǒ chídào le) - Xin lỗi, tôi đến muộn.",
  },
  {
    id: 24,
    hanzi: "多",
    pinyin: "duō",
    meaning_vi: "nhiều",
    example: "这里人很多 (Zhèlǐ rén hěn duō) - Ở đây rất đông người.",
  },
  {
    id: 25,
    hanzi: "多少",
    pinyin: "duōshao",
    meaning_vi: "bao nhiêu",
    example: "这个多少钱？ (Zhège duōshao qián?) - Cái này bao nhiêu tiền?",
  },
  {
    id: 26,
    hanzi: "儿子",
    pinyin: "érzi",
    meaning_vi: "con trai",
    example: "他有三个儿子 (Tā yǒu sān gè érzi) - Anh ấy có 3 đứa con trai.",
  },
  {
    id: 27,
    hanzi: "二",
    pinyin: "èr",
    meaning_vi: "số 2",
    example: "二点 (èr diǎn) - 2 giờ.",
  },
  {
    id: 28,
    hanzi: "饭店",
    pinyin: "fàndiàn",
    meaning_vi: "khách sạn, tiệm ăn",
    example: "去饭店吃饭 (Qù fàndiàn chī fàn) - Đi tiệm ăn.",
  },
  {
    id: 29,
    hanzi: "飞机",
    pinyin: "fēijī",
    meaning_vi: "máy bay",
    example: "坐飞机 (zuò fēijī) - Đi máy bay.",
  },
  {
    id: 30,
    hanzi: "分钟",
    pinyin: "fēnzhōng",
    meaning_vi: "phút",
    example: "十分钟 (shí fēnzhōng) - 10 phút.",
  },
  {
    id: 31,
    hanzi: "高兴",
    pinyin: "gāoxìng",
    meaning_vi: "vui vẻ",
    example: "认识你很高兴 (Rènshi nǐ hěn gāoxìng) - Rất vui được biết bạn.",
  },
  {
    id: 32,
    hanzi: "个",
    pinyin: "gè",
    meaning_vi: "cái (lượng từ)",
    example: "一个苹果 (yí gè píngguǒ) - Một quả táo.",
  },
  {
    id: 33,
    hanzi: "工作",
    pinyin: "gōngzuò",
    meaning_vi: "công việc, làm việc",
    example:
      "他在医院工作 (Tā zài yīyuàn gōngzuò) - Anh ấy làm việc ở bệnh viện.",
  },
  {
    id: 34,
    hanzi: "汉语",
    pinyin: "Hànyǔ",
    meaning_vi: "tiếng Trung",
    example: "学习汉语 (xuéxí Hànyǔ) - Học tiếng Trung.",
  },
  {
    id: 35,
    hanzi: "好",
    pinyin: "hǎo",
    meaning_vi: "tốt, khỏe, ngon",
    example: "你好 (Nǐ hǎo) - Chào bạn.",
  },
  {
    id: 36,
    hanzi: "号",
    pinyin: "hào",
    meaning_vi: "ngày, số",
    example: "今天五号 (Jīntiān wǔ hào) - Hôm nay ngày mùng 5.",
  },
  {
    id: 37,
    hanzi: "喝",
    pinyin: "hē",
    meaning_vi: "uống",
    example: "喝水 (hē shuǐ) - Uống nước.",
  },
  {
    id: 38,
    hanzi: "和",
    pinyin: "hé",
    meaning_vi: "và, với",
    example: "我和你 (Wǒ hé nǐ) - Tôi và bạn.",
  },
  {
    id: 39,
    hanzi: "很",
    pinyin: "hěn",
    meaning_vi: "rất",
    example: "他很高 (Tā hěn gāo) - Anh ấy rất cao.",
  },
  {
    id: 40,
    hanzi: "后面",
    pinyin: "hòumiàn",
    meaning_vi: "phía sau",
    example: "学校后面 (xuéxiào hòumiàn) - Phía sau trường học.",
  },
  {
    id: 41,
    hanzi: "回",
    pinyin: "huí",
    meaning_vi: "về",
    example: "回家 (huí jiā) - Về nhà.",
  },
  {
    id: 42,
    hanzi: "会",
    pinyin: "huì",
    meaning_vi: "biết, sẽ",
    example: "我会说汉语 (Wǒ huì shuō Hànyǔ) - Tôi biết nói tiếng Trung.",
  },
  {
    id: 43,
    hanzi: "几",
    pinyin: "jǐ",
    meaning_vi: "mấy",
    example: "几个人？ (jǐ gè rén?) - Mấy người?",
  },
  {
    id: 44,
    hanzi: "家",
    pinyin: "jiā",
    meaning_vi: "nhà, gia đình",
    example: "我爱我的家 (Wǒ ài wǒ de jiā) - Tôi yêu gia đình tôi.",
  },
  {
    id: 45,
    hanzi: "叫",
    pinyin: "jiào",
    meaning_vi: "gọi, tên là",
    example: "你叫什么名字？ (Nǐ jiào shénme míngzi?) - Bạn tên là gì?",
  },
  {
    id: 46,
    hanzi: "今天",
    pinyin: "jīntiān",
    meaning_vi: "hôm nay",
    example: "今天星期一 (Jīntiān xīngqī yī) - Hôm nay là thứ hai.",
  },
  {
    id: 47,
    hanzi: "九",
    pinyin: "jiǔ",
    meaning_vi: "số 9",
    example: "九块钱 (jiǔ kuài qián) - 9 tệ.",
  },
  {
    id: 48,
    hanzi: "开",
    pinyin: "kāi",
    meaning_vi: "mở, lái (xe)",
    example: "开车 (kāi chē) - Lái xe.",
  },
  {
    id: 49,
    hanzi: "看见",
    pinyin: "kànjiàn",
    meaning_vi: "nhìn thấy",
    example: "我看见他了 (Wǒ kànjiàn tā le) - Tôi nhìn thấy anh ấy rồi.",
  },
  {
    id: 50,
    hanzi: "块",
    pinyin: "kuài",
    meaning_vi: "đồng, tệ (đơn vị tiền)",
    example: "五块钱 (wǔ kuài qián) - 5 tệ.",
  },
  {
    id: 51,
    hanzi: "来",
    pinyin: "lái",
    meaning_vi: "đến",
    example: "他来到我家 (Tā lái dào wǒ jiā) - Anh ấy đến nhà tôi.",
  },
  {
    id: 52,
    hanzi: "老师",
    pinyin: "lǎoshī",
    meaning_vi: "giáo viên",
    example: "王老师很好 (Wáng lǎoshī hěn hǎo) - Thầy Vương rất tốt.",
  },
  {
    id: 53,
    hanzi: "了",
    pinyin: "le",
    meaning_vi: "rồi (trợ từ)",
    example: "我吃饭了 (Wǒ chī fàn le) - Tôi ăn cơm rồi.",
  },
  {
    id: 54,
    hanzi: "冷",
    pinyin: "lěng",
    meaning_vi: "lạnh",
    example: "今天很冷 (Jīntiān hěn lěng) - Hôm nay rất lạnh.",
  },
  {
    id: 55,
    hanzi: "里",
    pinyin: "lǐ",
    meaning_vi: "trong",
    example: "家里有人 (Jiā lǐ yǒu rén) - Trong nhà có người.",
  },
  {
    id: 56,
    hanzi: "零",
    pinyin: "líng",
    meaning_vi: "số 0",
    example: "二零二六 (èr líng èr liù) - 2026.",
  },
  {
    id: 57,
    hanzi: "六",
    pinyin: "liù",
    meaning_vi: "số 6",
    example: "六个苹果 (liù gè píngguǒ) - 6 quả táo.",
  },
  {
    id: 58,
    hanzi: "妈妈",
    pinyin: "māma",
    meaning_vi: "mẹ",
    example: "我妈妈在做饭 (Wǒ māma zài zuò fàn) - Mẹ tôi đang nấu cơm.",
  },
  {
    id: 59,
    hanzi: "吗",
    pinyin: "ma",
    meaning_vi: "không? (câu hỏi)",
    example: "你好吗？ (Nǐ hǎo ma?) - Bạn khỏe không?",
  },
  {
    id: 60,
    hanzi: "买",
    pinyin: "mǎi",
    meaning_vi: "mua",
    example: "我想买书 (Wǒ xiǎng mǎi shū) - Tôi muốn mua sách.",
  },
  {
    id: 61,
    hanzi: "猫",
    pinyin: "māo",
    meaning_vi: "con mèo",
    example: "那只猫很可爱 (Nà zhī māo hěn kě'ài) - Con mèo đó rất đáng yêu.",
  },
  {
    id: 62,
    hanzi: "没关系",
    pinyin: "méiguānxi",
    meaning_vi: "không sao đâu",
    example: "对不起！没关系 (Duìbuqǐ! Méiguānxi) - Xin lỗi! Không sao đâu.",
  },
  {
    id: 63,
    hanzi: "没有",
    pinyin: "méiyǒu",
    meaning_vi: "không có",
    example: "我没有钱 (Wǒ méiyǒu qián) - Tôi không có tiền.",
  },
  {
    id: 64,
    hanzi: "米饭",
    pinyin: "mǐfàn",
    meaning_vi: "cơm",
    example: "吃米饭 (chī mǐfàn) - Ăn cơm.",
  },
  {
    id: 65,
    hanzi: "名字",
    pinyin: "míngzi",
    meaning_vi: "tên",
    example: "你叫什么名字？ (Nǐ jiào shénme míngzi?) - Bạn tên là gì?",
  },
  {
    id: 66,
    hanzi: "明天",
    pinyin: "míngtiān",
    meaning_vi: "ngày mai",
    example: "明天见 (Míngtiān jiàn) - Hẹn gặp ngày mai.",
  },
  {
    id: 67,
    hanzi: "哪",
    pinyin: "nǎ",
    meaning_vi: "nào",
    example:
      "哪个人是你的老师？ (Nǎ gè rén shì nǐ de lǎoshī?) - Người nào là thầy của bạn?",
  },
  {
    id: 68,
    hanzi: "哪儿",
    pinyin: "nǎr",
    meaning_vi: "ở đâu",
    example: "你在哪儿？ (Nǐ zài nǎr?) - Bạn ở đâu?",
  },
  {
    id: 69,
    hanzi: "那",
    pinyin: "nà",
    meaning_vi: "kia, đó",
    example: "那是我的书 (Nà shì wǒ de shū) - Kia là sách của tôi.",
  },
  {
    id: 70,
    hanzi: "呢",
    pinyin: "ne",
    meaning_vi: "nhé, còn... thì sao",
    example: "你呢？ (Nǐ ne?) - Còn bạn thì sao?",
  },
  {
    id: 71,
    hanzi: "能",
    pinyin: "néng",
    meaning_vi: "có thể",
    example: "你能去吗？ (Nǐ néng qù ma?) - Bạn có thể đi không?",
  },
  {
    id: 72,
    hanzi: "你",
    pinyin: "nǐ",
    meaning_vi: "bạn",
    example: "你是学生吗？ (Nǐ shì xuésheng ma?) - Bạn là học sinh à?",
  },
  {
    id: 73,
    hanzi: "年",
    pinyin: "nián",
    meaning_vi: "năm",
    example: "三年了 (sān nián le) - 3 năm rồi.",
  },
  {
    id: 74,
    hanzi: "女儿",
    pinyin: "nǚ'ér",
    meaning_vi: "con gái",
    example: "他有两个女儿 (Tā yǒu liǎng gè nǚ'ér) - Anh ấy có 2 đứa con gái.",
  },
  {
    id: 75,
    hanzi: "朋友",
    pinyin: "péngyou",
    meaning_vi: "bạn bè",
    example:
      "他是我的好朋友 (Tā shì wǒ de hǎo péngyou) - Anh ấy là bạn thân của tôi.",
  },
  {
    id: 76,
    hanzi: "漂亮",
    pinyin: "piàoliang",
    meaning_vi: "đẹp",
    example: "衣服很漂亮 (Yīfu hěn piàoliang) - Quần áo rất đẹp.",
  },
  {
    id: 77,
    hanzi: "苹果",
    pinyin: "píngguǒ",
    meaning_vi: "quả táo",
    example: "吃苹果 (chī píngguǒ) - Ăn táo.",
  },
  {
    id: 78,
    hanzi: "七",
    pinyin: "qī",
    meaning_vi: "số 7",
    example: "七点钟 (qī diǎn zhōng) - 7 giờ.",
  },
  {
    id: 79,
    hanzi: "钱",
    pinyin: "qián",
    meaning_vi: "tiền",
    example: "多少钱？ (Duōshǎo qián?) - Bao nhiêu tiền?",
  },
  {
    id: 80,
    hanzi: "前面",
    pinyin: "qiánmiàn",
    meaning_vi: "phía trước",
    example: "他在前面 (Tā zài qiánmiàn) - Anh ấy ở phía trước.",
  },
  {
    id: 81,
    hanzi: "请",
    pinyin: "qǐng",
    meaning_vi: "mời",
    example: "请坐 (Qǐng zuò) - Mời ngồi.",
  },
  {
    id: 82,
    hanzi: "去",
    pinyin: "qù",
    meaning_vi: "đi",
    example: "我去书店 (Wǒ qù shūdiàn) - Tôi đi hiệu sách.",
  },
  {
    id: 83,
    hanzi: "热",
    pinyin: "rè",
    meaning_vi: "nóng",
    example: "今天很热 (Jīntiān hěn rè) - Hôm nay rất nóng.",
  },
  {
    id: 84,
    hanzi: "人",
    pinyin: "rén",
    meaning_vi: "người",
    example: "中国人 (Zhōngguó rén) - Người Trung Quốc.",
  },
  {
    id: 85,
    hanzi: "认识",
    pinyin: "rènshi",
    meaning_vi: "quen biết",
    example:
      "认识你很高兴 (Rènshi nǐ hěn gāoxìng) - Rất vui được quen biết bạn.",
  },
  {
    id: 86,
    hanzi: "三",
    pinyin: "sān",
    meaning_vi: "số 3",
    example: "三个人 (sān gè rén) - 3 người.",
  },
  {
    id: 87,
    hanzi: "商店",
    pinyin: "shāngdiàn",
    meaning_vi: "cửa hàng",
    example: "去商店买东西 (Qù shāngdiàn mǎi dōngxi) - Đi cửa hàng mua đồ.",
  },
  {
    id: 88,
    hanzi: "上",
    pinyin: "shàng",
    meaning_vi: "trên, lên",
    example: "桌子上 (zhuōzi shàng) - Trên bàn.",
  },
  {
    id: 89,
    hanzi: "上午",
    pinyin: "shàngwǔ",
    meaning_vi: "buổi sáng",
    example: "上午九点 (shàngwǔ jiǔ diǎn) - 9 giờ sáng.",
  },
  {
    id: 90,
    hanzi: "少",
    pinyin: "shǎo",
    meaning_vi: "ít",
    example: "人很少 (rén hěn shǎo) - Rất ít người.",
  },
  {
    id: 91,
    hanzi: "谁",
    pinyin: "shéi",
    meaning_vi: "ai",
    example:
      "谁是你的老师？ (Shéi shì nǐ de lǎoshī?) - Ai là thầy giáo của bạn?",
  },
  {
    id: 92,
    hanzi: "什么",
    pinyin: "shénme",
    meaning_vi: "cái gì",
    example: "这是什么？ (Zhè shì shénme?) - Đây là cái gì?",
  },
  {
    id: 93,
    hanzi: "十",
    pinyin: "shí",
    meaning_vi: "số 10",
    example: "十块钱 (shí kuài qián) - 10 tệ.",
  },
  {
    id: 94,
    hanzi: "时候",
    pinyin: "shíhou",
    meaning_vi: "lúc, khi",
    example: "什么时候？ (Shénme shíhou?) - Khi nào?",
  },
  {
    id: 95,
    hanzi: "是",
    pinyin: "shì",
    meaning_vi: "là",
    example: "我是学生 (Wǒ shì xuésheng) - Tôi là học sinh.",
  },
  {
    id: 96,
    hanzi: "书",
    pinyin: "shū",
    meaning_vi: "sách",
    example: "我看书 (Wǒ kàn shū) - Tôi đọc sách.",
  },
  {
    id: 97,
    hanzi: "水",
    pinyin: "shuǐ",
    meaning_vi: "nước",
    example: "喝水 (hē shuǐ) - Uống nước.",
  },
  {
    id: 98,
    hanzi: "水果",
    pinyin: "shuǐguǒ",
    meaning_vi: "hoa quả",
    example: "我想吃水果 (Wǒ xiǎng chī shuǐguǒ) - Tôi muốn ăn hoa quả.",
  },
  {
    id: 99,
    hanzi: "睡觉",
    pinyin: "shuìjiào",
    meaning_vi: "ngủ",
    example: "十一点睡觉 (shíyī diǎn shuìjiào) - Ngủ lúc 11 giờ.",
  },
  {
    id: 100,
    hanzi: "说",
    pinyin: "shuō",
    meaning_vi: "nói",
    example: "说汉语 (shuō Hànyǔ) - Nói tiếng Trung.",
  },
  {
    id: 101,
    hanzi: "说话",
    pinyin: "shuōhuà",
    meaning_vi: "nói chuyện",
    example: "别说话 (Bié shuōhuà) - Đừng nói chuyện.",
  },
  {
    id: 102,
    hanzi: "四",
    pinyin: "sì",
    meaning_vi: "số 4",
    example: "四个人 (sì gè rén) - 4 người.",
  },
  {
    id: 103,
    hanzi: "岁",
    pinyin: "suì",
    meaning_vi: "tuổi",
    example: "他二十岁 (Tā èrshí suì) - Anh ấy 20 tuổi.",
  },
  {
    id: 104,
    hanzi: "他",
    pinyin: "tā",
    meaning_vi: "anh ấy, ông ấy",
    example:
      "他是我的老师 (Tā shì wǒ de lǎoshī) - Ông ấy là thầy giáo của tôi.",
  },
  {
    id: 105,
    hanzi: "她",
    pinyin: "tā",
    meaning_vi: "cô ấy, bà ấy",
    example: "她很漂亮 (Tā hěn piàoliang) - Cô ấy rất đẹp.",
  },
  {
    id: 106,
    hanzi: "太",
    pinyin: "tài",
    meaning_vi: "quá, lắm",
    example: "太好了 (Tài hǎo le) - Tốt quá rồi.",
  },
  {
    id: 107,
    hanzi: "天气",
    pinyin: "tiānqì",
    meaning_vi: "thời tiết",
    example:
      "今天天气很好 (Jīntiān tiānqì hěn hǎo) - Thời tiết hôm nay rất tốt.",
  },
  {
    id: 108,
    hanzi: "听",
    pinyin: "tīng",
    meaning_vi: "nghe",
    example: "你听我说 (Nǐ tīng wǒ shuō) - Bạn nghe tôi nói này.",
  },
  {
    id: 109,
    hanzi: "同学",
    pinyin: "tóngxué",
    meaning_vi: "bạn cùng học",
    example:
      "他们是我的同学 (Tāmen shì wǒ de tóngxué) - Họ là bạn cùng lớp của tôi.",
  },
  {
    id: 110,
    hanzi: "喂",
    pinyin: "wèi",
    meaning_vi: "alo, này",
    example: "喂，你好 (Wèi, nǐ hǎo) - Alo, chào bạn.",
  },
  {
    id: 111,
    hanzi: "我",
    pinyin: "wǒ",
    meaning_vi: "tôi, ta",
    example: "我是越南人 (Wǒ shì Yuènán rén) - Tôi là người Việt Nam.",
  },
  {
    id: 112,
    hanzi: "我们",
    pinyin: "wǒmen",
    meaning_vi: "chúng tôi",
    example: "我们去商店吧 (Wǒmen qù shāngdiàn ba) - Chúng ta đi cửa hàng nhé.",
  },
  {
    id: 113,
    hanzi: "五",
    pinyin: "wǔ",
    meaning_vi: "số 5",
    example: "五个苹果 (wǔ gè píngguǒ) - 5 quả táo.",
  },
  {
    id: 114,
    hanzi: "喜欢",
    pinyin: "xǐhuan",
    meaning_vi: "thích",
    example: "我喜欢学汉语 (Wǒ xǐhuan xué Hànyǔ) - Tôi thích học tiếng Trung.",
  },
  {
    id: 115,
    hanzi: "下",
    pinyin: "xià",
    meaning_vi: "dưới, xuống",
    example: "下雨了 (xiàyǔ le) - Mưa rồi.",
  },
  {
    id: 116,
    hanzi: "下午",
    pinyin: "xiàwǔ",
    meaning_vi: "buổi chiều",
    example: "下午三点 (xiàwǔ sān diǎn) - 3 giờ chiều.",
  },
  {
    id: 117,
    hanzi: "下雨",
    pinyin: "xiàyǔ",
    meaning_vi: "mưa",
    example: "外面在下雨 (Wàimiàn zài xiàyǔ) - Bên ngoài đang mưa.",
  },
  {
    id: 118,
    hanzi: "先生",
    pinyin: "xiānsheng",
    meaning_vi: "ông, ngài, chồng",
    example:
      "王先生不在家 (Wáng xiānsheng bú zài jiā) - Ông Vương không có ở nhà.",
  },
  {
    id: 119,
    hanzi: "现在",
    pinyin: "xiànzài",
    meaning_vi: "bây giờ",
    example: "现在几点？ (Xiànzài jǐ diǎn?) - Bây giờ là mấy giờ?",
  },
  {
    id: 120,
    hanzi: "想",
    pinyin: "xiǎng",
    meaning_vi: "muốn, nhớ, nghĩ",
    example: "我想去北京 (Wǒ xiǎng qù Běijīng) - Tôi muốn đi Bắc Kinh.",
  },
  {
    id: 121,
    hanzi: "小",
    pinyin: "xiǎo",
    meaning_vi: "nhỏ, bé",
    example: "这个杯子很小 (Zhège bēizi hěn xiǎo) - Cái cốc này rất nhỏ.",
  },
  {
    id: 122,
    hanzi: "小姐",
    pinyin: "xiǎojiě",
    meaning_vi: "cô, tiểu thư",
    example:
      "王小姐喜欢喝茶 (Wáng xiǎojiě xǐhuan hē chá) - Cô Vương thích uống trà.",
  },
  {
    id: 123,
    hanzi: "些",
    pinyin: "xiē",
    meaning_vi: "một số, một ít",
    example:
      "这些书是我的 (Zhèxiē shū shì wǒ de) - Những cuốn sách này là của tôi.",
  },
  {
    id: 124,
    hanzi: "写",
    pinyin: "xiě",
    meaning_vi: "viết",
    example: "你在写什么？ (Nǐ zài xiě shénme?) - Bạn đang viết gì thế?",
  },
  {
    id: 125,
    hanzi: "谢谢",
    pinyin: "xièxie",
    meaning_vi: "cảm ơn",
    example: "谢谢你的帮助 (Xièxie nǐ de bāngzhù) - Cảm ơn sự giúp đỡ của bạn.",
  },
  {
    id: 126,
    hanzi: "星期",
    pinyin: "xīngqī",
    meaning_vi: "thứ, tuần",
    example: "星期一 (xīngqī yī) - Thứ hai.",
  },
  {
    id: 127,
    hanzi: "学生",
    pinyin: "xuésheng",
    meaning_vi: "học sinh, sinh viên",
    example:
      "我们都是学生 (Wǒmen dōu shì xuésheng) - Chúng tôi đều là học sinh.",
  },
  {
    id: 128,
    hanzi: "学习",
    pinyin: "xuéxí",
    meaning_vi: "học tập",
    example: "他在学习汉语 (Tā zài xuéxí Hànyǔ) - Anh ấy đang học tiếng Trung.",
  },
  {
    id: 129,
    hanzi: "学校",
    pinyin: "xuéxiào",
    meaning_vi: "trường học",
    example: "去学校 (qù xuéxiào) - Đi đến trường.",
  },
  {
    id: 130,
    hanzi: "一",
    pinyin: "yī",
    meaning_vi: "số 1",
    example: "一个苹果 (yí gè píngguǒ) - Một quả táo.",
  },
  {
    id: 131,
    hanzi: "衣服",
    pinyin: "yīfu",
    meaning_vi: "quần áo",
    example: "买衣服 (mǎi yīfu) - Mua quần áo.",
  },
  {
    id: 132,
    hanzi: "医生",
    pinyin: "yīshēng",
    meaning_vi: "bác sĩ",
    example: "我妈妈是医生 (Wǒ māma shì yīshēng) - Mẹ tôi là bác sĩ.",
  },
  {
    id: 133,
    hanzi: "医院",
    pinyin: "yīyuàn",
    meaning_vi: "bệnh viện",
    example: "去医院 (qù yīyuàn) - Đi bệnh viện.",
  },
  {
    id: 134,
    hanzi: "椅子",
    pinyin: "yǐzi",
    meaning_vi: "cái ghế",
    example: "坐在椅子上 (zuò zài yǐzi shàng) - Ngồi trên ghế.",
  },
  {
    id: 135,
    hanzi: "有",
    pinyin: "yǒu",
    meaning_vi: "có",
    example: "我有书 (Wǒ yǒu shū) - Tôi có sách.",
  },
  {
    id: 136,
    hanzi: "月",
    pinyin: "yuè",
    meaning_vi: "tháng",
    example: "八月 (bā yuè) - Tháng tám.",
  },
  {
    id: 137,
    hanzi: "再见",
    pinyin: "zàijiàn",
    meaning_vi: "tạm biệt",
    example: "老师，再见 (Lǎoshī, zàijiàn) - Thầy giáo, tạm biệt.",
  },
  {
    id: 138,
    hanzi: "在",
    pinyin: "zài",
    meaning_vi: "ở, đang",
    example: "他在家 (Tā zài jiā) - Anh ấy ở nhà.",
  },
  {
    id: 139,
    hanzi: "怎么",
    pinyin: "zěnme",
    meaning_vi: "thế nào, làm sao",
    example: "这个字怎么写？ (Zhège zì zěnme xiě?) - Chữ này viết thế nào?",
  },
  {
    id: 140,
    hanzi: "怎么样",
    pinyin: "zěnmeyàng",
    meaning_vi: "như thế nào",
    example: "天气怎么样？ (Tiānqì zěnmeyàng?) - Thời tiết thế nào?",
  },
  {
    id: 141,
    hanzi: "这",
    pinyin: "zhè",
    meaning_vi: "này, đây",
    example: "这是我的猫 (Zhè shì wǒ de māo) - Đây là con mèo của tôi.",
  },
  {
    id: 142,
    hanzi: "中国",
    pinyin: "Zhōngguó",
    meaning_vi: "Trung Quốc",
    example: "中国很大 (Zhōngguó hěn dà) - Trung Quốc rất lớn.",
  },
  {
    id: 143,
    hanzi: "中午",
    pinyin: "zhōngwǔ",
    meaning_vi: "buổi trưa",
    example: "中午吃饭 (zhōngwǔ chī fàn) - Ăn cơm trưa.",
  },
  {
    id: 144,
    hanzi: "住",
    pinyin: "zhù",
    meaning_vi: "ở, cư trú",
    example: "你住在哪儿？ (Nǐ zhù zài nǎr?) - Bạn sống ở đâu?",
  },
  {
    id: 145,
    hanzi: "桌子",
    pinyin: "zhuōzi",
    meaning_vi: "cái bàn",
    example: "桌子上放着书 (Zhuōzi shàng fàngzhe shū) - Trên bàn có đặt sách.",
  },
  {
    id: 146,
    hanzi: "字",
    pinyin: "zì",
    meaning_vi: "chữ, từ",
    example: "汉字 (Hànzì) - Chữ Hán.",
  },
  {
    id: 147,
    hanzi: "昨天",
    pinyin: "zuótiān",
    meaning_vi: "hôm qua",
    example: "昨天没下雨 (Zuótiān méi xiàyǔ) - Hôm qua không mưa.",
  },
  {
    id: 148,
    hanzi: "做",
    pinyin: "zuò",
    meaning_vi: "làm",
    example: "你在做什么？ (Nǐ zài zuò shénme?) - Bạn đang làm gì đấy?",
  },
  {
    id: 149,
    hanzi: "坐",
    pinyin: "zuò",
    meaning_vi: "ngồi",
    example: "请坐 (Qǐng zuò) - Mời ngồi.",
  },
  {
    id: 150,
    hanzi: "吧",
    pinyin: "ba",
    meaning_vi: "nhé, đi (trợ từ)",
    example: "走吧 (zǒu ba) - Đi thôi.",
  },
  {
    id: 151,
    hanzi: "白",
    pinyin: "bái",
    meaning_vi: "trắng",
    example: "白色的衣服 (báisè de yīfu) - Quần áo màu trắng.",
  },
  {
    id: 152,
    hanzi: "百",
    pinyin: "bǎi",
    meaning_vi: "trăm",
    example: "一百块钱 (yìbǎi kuài qián) - Một trăm tệ.",
  },
  {
    id: 153,
    hanzi: "帮助",
    pinyin: "bāngzhù",
    meaning_vi: "giúp đỡ",
    example: "谢谢你的帮助 (Xièxie nǐ de bāngzhù) - Cảm ơn sự giúp đỡ của bạn.",
  },
  {
    id: 154,
    hanzi: "报纸",
    pinyin: "bàozhǐ",
    meaning_vi: "tờ báo",
    example: "看报纸 (kàn bàozhǐ) - Đọc báo.",
  },
  {
    id: 155,
    hanzi: "比",
    pinyin: "bǐ",
    meaning_vi: "so với",
    example: "今天比昨天热 (Jīntiān bǐ zuótiān rè) - Hôm nay nóng hơn hôm qua.",
  },
  {
    id: 156,
    hanzi: "别",
    pinyin: "bié",
    meaning_vi: "đừng, cái khác",
    example: "别走了 (bié zǒu le) - Đừng đi nữa.",
  },
  {
    id: 157,
    hanzi: "长",
    pinyin: "cháng",
    meaning_vi: "dài",
    example: "这条路很长 (zhè tiáo lù hěn cháng) - Con đường này rất dài.",
  },
  {
    id: 158,
    hanzi: "唱歌",
    pinyin: "chànggē",
    meaning_vi: "hát",
    example: "她喜欢唱歌 (tā xǐhuan chànggē) - Cô ấy thích hát.",
  },
  {
    id: 159,
    hanzi: "出",
    pinyin: "chū",
    meaning_vi: "ra, xuất",
    example: "出去 (chūqù) - Đi ra ngoài.",
  },
  {
    id: 160,
    hanzi: "穿",
    pinyin: "chuān",
    meaning_vi: "mặc, xỏ (giày/tất)",
    example: "穿衣服 (chuān yīfu) - Mặc quần áo.",
  },
  {
    id: 161,
    hanzi: "次",
    pinyin: "cì",
    meaning_vi: "lần",
    example: "我去过一次 (wǒ qùguo yí cì) - Tôi đã đi một lần.",
  },
  {
    id: 162,
    hanzi: "从",
    pinyin: "cóng",
    meaning_vi: "từ (nơi chốn/thời gian)",
    example:
      "从北京到上海 (cóng Běijīng dào Shànghǎi) - Từ Bắc Kinh đến Thượng Hải.",
  },
  {
    id: 163,
    hanzi: "错",
    pinyin: "cuò",
    meaning_vi: "sai, nhầm",
    example: "你说错了 (nǐ shuō cuò le) - Bạn nói sai rồi.",
  },
  {
    id: 164,
    hanzi: "打篮球",
    pinyin: "dǎ lánqiú",
    meaning_vi: "đánh bóng rổ",
    example:
      "我们去打篮球吧 (wǒmen qù dǎ lánqiú ba) - Chúng ta đi chơi bóng rổ đi.",
  },
  {
    id: 165,
    hanzi: "大家",
    pinyin: "dàjiā",
    meaning_vi: "mọi người",
    example: "大家好 (dàjiā hǎo) - Chào mọi người.",
  },
  {
    id: 166,
    hanzi: "到",
    pinyin: "dào",
    meaning_vi: "đến",
    example: "我到家了 (wǒ dào jiā le) - Tôi về đến nhà rồi.",
  },
  {
    id: 167,
    hanzi: "得",
    pinyin: "de",
    meaning_vi: "trợ từ kết cấu",
    example: "跑得很快 (pǎo de hěn kuài) - Chạy rất nhanh.",
  },
  {
    id: 168,
    hanzi: "等",
    pinyin: "děng",
    meaning_vi: "đợi, chờ",
    example: "等等我 (děng děng wǒ) - Đợi tôi với.",
  },
  {
    id: 169,
    hanzi: "弟弟",
    pinyin: "dìdi",
    meaning_vi: "em trai",
    example: "我弟弟十岁 (wǒ dìdi shí suì) - Em trai tôi 10 tuổi.",
  },
  {
    id: 170,
    hanzi: "第一",
    pinyin: "dì-yī",
    meaning_vi: "thứ nhất",
    example: "第一名 (dì-yī míng) - Hạng nhất.",
  },
  {
    id: 171,
    hanzi: "懂",
    pinyin: "dǒng",
    meaning_vi: "hiểu",
    example: "你听懂了吗？ (nǐ tīng dǒng le ma?) - Bạn nghe có hiểu không?",
  },
  {
    id: 172,
    hanzi: "对",
    pinyin: "duì",
    meaning_vi: "đúng, đối với",
    example: "你说得很对 (nǐ shuō de hěn duì) - Bạn nói rất đúng.",
  },
  {
    id: 173,
    hanzi: "房间",
    pinyin: "fángjiān",
    meaning_vi: "phòng",
    example: "进房间 (jìn fángjiān) - Vào phòng.",
  },
  {
    id: 174,
    hanzi: "非常",
    pinyin: "fēicháng",
    meaning_vi: "rất, cực kỳ",
    example: "非常漂亮 (fēicháng piàoliang) - Cực kỳ xinh đẹp.",
  },
  {
    id: 175,
    hanzi: "服务员",
    pinyin: "fúwùyuán",
    meaning_vi: "người phục vụ",
    example:
      "服务员，请给我水 (fúwùyuán, qǐng gěi wǒ shuǐ) - Phục vụ, cho tôi xin nước.",
  },
  {
    id: 176,
    hanzi: "高",
    pinyin: "gāo",
    meaning_vi: "cao",
    example: "他很高 (tā hěn gāo) - Anh ấy rất cao.",
  },
  {
    id: 177,
    hanzi: "告诉",
    pinyin: "gàosu",
    meaning_vi: "nói cho biết",
    example: "请告诉我 (qǐng gàosu wǒ) - Xin hãy nói cho tôi biết.",
  },
  {
    id: 178,
    hanzi: "哥哥",
    pinyin: "gēge",
    meaning_vi: "anh trai",
    example: "我哥哥在工作 (wǒ gēge zài gōngzuò) - Anh trai tôi đang làm việc.",
  },
  {
    id: 179,
    hanzi: "给",
    pinyin: "gěi",
    meaning_vi: "cho",
    example: "给你钱 (gěi nǐ qián) - Cho bạn tiền này.",
  },
  {
    id: 180,
    hanzi: "公共汽车",
    pinyin: "gōnggòng qìchē",
    meaning_vi: "xe buýt",
    example: "坐公共汽车 (zuò gōnggòng qìchē) - Đi xe buýt.",
  },
  {
    id: 181,
    hanzi: "公司",
    pinyin: "gōngsī",
    meaning_vi: "công ty",
    example: "他在公司 (tā zài gōngsī) - Anh ấy ở công ty.",
  },
  {
    id: 182,
    hanzi: "狗",
    pinyin: "gǒu",
    meaning_vi: "con chó",
    example: "我家有一只狗 (wǒ jiā yǒu yì zhī gǒu) - Nhà tôi có một con chó.",
  },
  {
    id: 183,
    hanzi: "贵",
    pinyin: "guì",
    meaning_vi: "đắt, quý",
    example: "太贵了 (tài guì le) - Đắt quá.",
  },
  {
    id: 184,
    hanzi: "过",
    pinyin: "guò",
    meaning_vi: "qua, từng",
    example: "过去 (guòqù) - Đi qua.",
  },
  {
    id: 185,
    hanzi: "还",
    pinyin: "hái",
    meaning_vi: "vẫn, còn",
    example: "他还没来 (tā hái méi lái) - Anh ấy vẫn chưa đến.",
  },
  {
    id: 186,
    hanzi: "孩子",
    pinyin: "háizi",
    meaning_vi: "trẻ con",
    example: "小孩子 (xiǎo háizi) - Đứa trẻ nhỏ.",
  },
  {
    id: 187,
    hanzi: "好吃",
    pinyin: "hǎochī",
    meaning_vi: "ngon",
    example:
      "中国菜很好吃 (Zhōngguó cài hěn hǎochī) - Món Trung Quốc rất ngon.",
  },
  {
    id: 188,
    hanzi: "黑",
    pinyin: "hēi",
    meaning_vi: "đen",
    example: "黑色的猫 (hēisè de māo) - Con mèo màu đen.",
  },
  {
    id: 189,
    hanzi: "红",
    pinyin: "hóng",
    meaning_vi: "đỏ",
    example: "红色的苹果 (hóngsè de píngguǒ) - Quả táo màu đỏ.",
  },
  {
    id: 190,
    hanzi: "火车站",
    pinyin: "huǒchēzhàn",
    meaning_vi: "ga tàu hỏa",
    example: "去火车站 (qù huǒchēzhàn) - Đi ga tàu hỏa.",
  },
  {
    id: 191,
    hanzi: "机场",
    pinyin: "jīchǎng",
    meaning_vi: "sân bay",
    example: "在机场等他 (zài jīchǎng děng tā) - Đợi anh ấy ở sân bay.",
  },
  {
    id: 192,
    hanzi: "鸡蛋",
    pinyin: "jīdàn",
    meaning_vi: "trứng gà",
    example: "吃个鸡蛋 (chī gè jīdàn) - Ăn một quả trứng gà.",
  },
  {
    id: 193,
    hanzi: "件",
    pinyin: "jiàn",
    meaning_vi: "chiếc, bộ (lượng từ quần áo)",
    example: "一件衣服 (yí jiàn yīfu) - Một bộ quần áo.",
  },
  {
    id: 194,
    hanzi: "教室",
    pinyin: "jiàoshì",
    meaning_vi: "lớp học",
    example: "在教室学习 (zài jiàoshì xuéxí) - Học trong lớp.",
  },
  {
    id: 195,
    hanzi: "姐姐",
    pinyin: "jiějie",
    meaning_vi: "chị gái",
    example: "我姐姐很漂亮 (wǒ jiějie hěn piàoliang) - Chị gái tôi rất xinh.",
  },
  {
    id: 196,
    hanzi: "介绍",
    pinyin: "jièshào",
    meaning_vi: "giới thiệu",
    example:
      "我来介绍一下 (wǒ lái jièshào yíxià) - Để tôi giới thiệu một chút.",
  },
  {
    id: 197,
    hanzi: "近",
    pinyin: "jìn",
    meaning_vi: "gần",
    example:
      "我家离学校很近 (wǒ jiā lí xuéxiào hěn jìn) - Nhà tôi cách trường rất gần.",
  },
  {
    id: 198,
    hanzi: "进",
    pinyin: "jìn",
    meaning_vi: "vào",
    example: "请进 (qǐng jìn) - Mời vào.",
  },
  {
    id: 199,
    hanzi: "就",
    pinyin: "jiù",
    meaning_vi: "thì, ngay",
    example: "我就去 (wǒ jiù qù) - Tôi đi ngay đây.",
  },
  {
    id: 200,
    hanzi: "觉得",
    pinyin: "juéde",
    meaning_vi: "cảm thấy",
    example: "我觉得很累 (wǒ juéde hěn lèi) - Tôi thấy rất mệt.",
  },
  {
    id: 201,
    hanzi: "咖啡",
    pinyin: "kāfēi",
    meaning_vi: "cà phê",
    example: "喝杯咖啡 (hē bēi kāfēi) - Uống cốc cà phê.",
  },
  {
    id: 202,
    hanzi: "开始",
    pinyin: "kāishǐ",
    meaning_vi: "bắt đầu",
    example: "我们开始吧 (wǒmen kāishǐ ba) - Chúng ta bắt đầu thôi.",
  },
  {
    id: 203,
    hanzi: "考试",
    pinyin: "kǎoshì",
    meaning_vi: "thi cử, kiểm tra",
    example: "明天有考试 (míngtiān yǒu kǎoshì) - Ngày mai có bài thi.",
  },
  {
    id: 204,
    hanzi: "可能",
    pinyin: "kěnéng",
    meaning_vi: "có thể, có lẽ",
    example: "他可能不来了 (tā kěnéng bù lái le) - Có lẽ anh ấy không đến nữa.",
  },
  {
    id: 205,
    hanzi: "可以",
    pinyin: "kěyǐ",
    meaning_vi: "có thể, được phép",
    example: "我可以进来吗？ (wǒ kěyǐ jìnlái ma?) - Tôi có thể vào không?",
  },
  {
    id: 206,
    hanzi: "课",
    pinyin: "kè",
    meaning_vi: "bài học, môn học",
    example: "上汉语课 (shàng Hànyǔ kè) - Lên lớp tiếng Trung.",
  },
  {
    id: 207,
    hanzi: "快",
    pinyin: "kuài",
    meaning_vi: "nhanh",
    example: "跑得很快 (pǎo de hěn kuài) - Chạy rất nhanh.",
  },
  {
    id: 208,
    hanzi: "快乐",
    pinyin: "kuàilè",
    meaning_vi: "vui vẻ, hạnh phúc",
    example: "生日快乐 (shēngrì kuàilè) - Sinh nhật vui vẻ.",
  },
  {
    id: 209,
    hanzi: "累",
    pinyin: "lèi",
    meaning_vi: "mệt",
    example: "我很累 (wǒ hěn lèi) - Tôi rất mệt.",
  },
  {
    id: 210,
    hanzi: "离",
    pinyin: "lí",
    meaning_vi: "cách, lìa xa",
    example: "我家离学校远 (wǒ jiā lí xuéxiào yuǎn) - Nhà tôi cách trường xa.",
  },
  {
    id: 211,
    hanzi: "两",
    pinyin: "liǎng",
    meaning_vi: "hai (dùng với lượng từ)",
    example: "两个月 (liǎng gè yuè) - Hai tháng.",
  },
  {
    id: 212,
    hanzi: "路",
    pinyin: "lù",
    meaning_vi: "đường đi",
    example: "路上小心 (lùshàng xiǎoxīn) - Đi đường cẩn thận.",
  },
  {
    id: 213,
    hanzi: "旅游",
    pinyin: "lǚyóu",
    meaning_vi: "du lịch",
    example: "去北京旅游 (qù Běijīng lǚyóu) - Đi du lịch Bắc Kinh.",
  },
  {
    id: 214,
    hanzi: "卖",
    pinyin: "mài",
    meaning_vi: "bán",
    example: "卖水果 (mài shuǐguǒ) - Bán hoa quả.",
  },
  {
    id: 215,
    hanzi: "慢",
    pinyin: "màn",
    meaning_vi: "chậm",
    example: "慢走 (màn zǒu) - Đi thong thả (lời chào).",
  },
  {
    id: 216,
    hanzi: "忙",
    pinyin: "máng",
    meaning_vi: "bận",
    example: "你忙吗？ (nǐ máng ma?) - Bạn bận không?",
  },
  {
    id: 217,
    hanzi: "每",
    pinyin: "měi",
    meaning_vi: "mỗi",
    example: "每天 (měitiān) - Mỗi ngày.",
  },
  {
    id: 218,
    hanzi: "妹妹",
    pinyin: "mèimei",
    meaning_vi: "em gái",
    example: "我妹妹很漂亮 (wǒ mèimei hěn piàoliang) - Em gái tôi rất xinh.",
  },
  {
    id: 219,
    hanzi: "门",
    pinyin: "mén",
    meaning_vi: "cửa",
    example: "开门 (kāi mén) - Mở cửa.",
  },
  {
    id: 220,
    hanzi: "男",
    pinyin: "nán",
    meaning_vi: "nam, đàn ông",
    example: "男学生 (nán xuésheng) - Nam sinh.",
  },
  {
    id: 221,
    hanzi: "您",
    pinyin: "nín",
    meaning_vi: "ngài, ông (kính trọng)",
    example: "老师，您好 (lǎoshī, nín hǎo) - Chào thầy/cô ạ.",
  },
  {
    id: 222,
    hanzi: "牛奶",
    pinyin: "niúnǎi",
    meaning_vi: "sữa bò",
    example: "喝牛奶 (hē niúnǎi) - Uống sữa.",
  },
  {
    id: 223,
    hanzi: "女",
    pinyin: "nǚ",
    meaning_vi: "nữ, phụ nữ",
    example: "女孩子 (nǚ háizi) - Bé gái.",
  },
  {
    id: 224,
    hanzi: "旁边",
    pinyin: "pángbiān",
    meaning_vi: "bên cạnh",
    example: "他在我旁边 (tā zài wǒ pángbiān) - Anh ấy ở cạnh tôi.",
  },
  {
    id: 225,
    hanzi: "跑步",
    pinyin: "pǎobù",
    meaning_vi: "chạy bộ",
    example: "每天跑步 (měitiān pǎobù) - Chạy bộ mỗi ngày.",
  },
  {
    id: 226,
    hanzi: "便宜",
    pinyin: "piányi",
    meaning_vi: "rẻ",
    example: "很便宜 (hěn piányi) - Rất rẻ.",
  },
  {
    id: 227,
    hanzi: "票",
    pinyin: "piào",
    meaning_vi: "vé",
    example: "买票 (mǎi piào) - Mua vé.",
  },
  {
    id: 228,
    hanzi: "妻子",
    pinyin: "qīzi",
    meaning_vi: "vợ",
    example: "我妻子是老师 (wǒ qīzi shì lǎoshī) - Vợ tôi là giáo viên.",
  },
  {
    id: 229,
    hanzi: "起床",
    pinyin: "qǐchuáng",
    meaning_vi: "ngủ dậy",
    example: "六点起床 (liù diǎn qǐchuáng) - 6 giờ ngủ dậy.",
  },
  {
    id: 230,
    hanzi: "千",
    pinyin: "qiān",
    meaning_vi: "nghìn",
    example: "五千块 (wǔqiān kuài) - Năm nghìn tệ.",
  },
  {
    id: 231,
    hanzi: "晴",
    pinyin: "qíng",
    meaning_vi: "nắng, trời quang",
    example: "晴天 (qíngtiān) - Ngày nắng.",
  },
  {
    id: 232,
    hanzi: "去年",
    pinyin: "qùnián",
    meaning_vi: "năm ngoái",
    example:
      "去年我去了北京 (qùnián wǒ qùle Běijīng) - Năm ngoái tôi đi Bắc Kinh.",
  },
  {
    id: 233,
    hanzi: "让",
    pinyin: "ràng",
    meaning_vi: "cho phép, bảo, nhường",
    example: "让他进来 (ràng tā jìnlái) - Bảo anh ấy vào đi.",
  },
  {
    id: 234,
    hanzi: "上班",
    pinyin: "shàngbān",
    meaning_vi: "đi làm",
    example: "我去上班 (wǒ qù shàngbān) - Tôi đi làm.",
  },
  {
    id: 235,
    hanzi: "身体",
    pinyin: "shēntǐ",
    meaning_vi: "thân thể, sức khỏe",
    example: "身体好吗？ (shēntǐ hǎo ma?) - Sức khỏe tốt không?",
  },
  {
    id: 236,
    hanzi: "生病",
    pinyin: "shēngbìng",
    meaning_vi: "ốm, bệnh",
    example: "我生病了 (wǒ shēngbìng le) - Tôi bị ốm rồi.",
  },
  {
    id: 237,
    hanzi: "生日",
    pinyin: "shēngrì",
    meaning_vi: "sinh nhật",
    example:
      "今天是我生日 (jīntiān shì wǒ shēngrì) - Hôm nay là sinh nhật tôi.",
  },
  {
    id: 238,
    hanzi: "时间",
    pinyin: "shíjiān",
    meaning_vi: "thời gian",
    example: "没时间 (méi shíjiān) - Không có thời gian.",
  },
  {
    id: 239,
    hanzi: "事情",
    pinyin: "shìqing",
    meaning_vi: "sự việc, việc",
    example: "什么事情？ (shénme shìqing?) - Việc gì thế?",
  },
  {
    id: 240,
    hanzi: "手表",
    pinyin: "shǒubiǎo",
    meaning_vi: "đồng hồ đeo tay",
    example: "买手表 (mǎi shǒubiǎo) - Mua đồng hồ.",
  },
  {
    id: 241,
    hanzi: "手机",
    pinyin: "shǒujī",
    meaning_vi: "điện thoại di động",
    example: "玩手机 (wán shǒujī) - Nghịch điện thoại.",
  },
  {
    id: 242,
    hanzi: "说话",
    pinyin: "shuōhuà",
    meaning_vi: "nói chuyện",
    example: "在说话 (zài shuōhuà) - Đang nói chuyện.",
  },
  {
    id: 243,
    hanzi: "送",
    pinyin: "sòng",
    meaning_vi: "tặng, tiễn",
    example: "送礼物 (sòng lǐwù) - Tặng quà.",
  },
  {
    id: 244,
    hanzi: "虽然",
    pinyin: "suīrán",
    meaning_vi: "mặc dù",
    example: "虽然很冷 (suīrán hěn lěng) - Mặc dù rất lạnh.",
  },
  {
    id: 245,
    hanzi: "但是",
    pinyin: "dànshì",
    meaning_vi: "nhưng",
    example: "但是很开心 (dànshì hěn kāixīn) - Nhưng rất vui.",
  },
  {
    id: 246,
    hanzi: "它",
    pinyin: "tā",
    meaning_vi: "nó (chỉ vật/con vật)",
    example: "它是我的狗 (tā shì wǒ de gǒu) - Nó là con chó của tôi.",
  },
  {
    id: 247,
    hanzi: "踢足球",
    pinyin: "tī zúqiú",
    meaning_vi: "đá bóng",
    example: "去踢足球吧 (qù tī zúqiú ba) - Đi đá bóng đi.",
  },
  {
    id: 248,
    hanzi: "题",
    pinyin: "tí",
    meaning_vi: "đề bài, câu hỏi",
    example: "这道题很难 (zhè dào tí hěn nán) - Câu này rất khó.",
  },
  {
    id: 249,
    hanzi: "跳舞",
    pinyin: "tiàowǔ",
    meaning_vi: "nhảy múa",
    example: "喜欢跳舞 (xǐhuan tiàowǔ) - Thích nhảy múa.",
  },
  {
    id: 250,
    hanzi: "外",
    pinyin: "wài",
    meaning_vi: "ngoài",
    example: "外面 (wàimiàn) - Bên ngoài.",
  },
  {
    id: 251,
    hanzi: "完",
    pinyin: "wán",
    meaning_vi: "xong, hết",
    example: "看完了 (kàn wán le) - Xem xong rồi.",
  },
  {
    id: 252,
    hanzi: "玩",
    pinyin: "wán",
    meaning_vi: "chơi",
    example: "去外面玩 (qù wàimiàn wán) - Đi ra ngoài chơi.",
  },
  {
    id: 253,
    hanzi: "晚上",
    pinyin: "wǎnshang",
    meaning_vi: "buổi tối",
    example: "今天晚上 (jīntiān wǎnshang) - Tối hôm nay.",
  },
  {
    id: 254,
    hanzi: "为什么",
    pinyin: "wèishénme",
    meaning_vi: "tại sao",
    example: "为什么不来？ (wèishénme bù lái?) - Tại sao không đến?",
  },
  {
    id: 255,
    hanzi: "问",
    pinyin: "wèn",
    meaning_vi: "hỏi",
    example: "问老师 (wèn lǎoshī) - Hỏi thầy giáo.",
  },
  {
    id: 256,
    hanzi: "问题",
    pinyin: "wèntí",
    meaning_vi: "vấn đề, câu hỏi",
    example: "没有问题 (méiyǒu wèntí) - Không có vấn đề gì.",
  },
  {
    id: 257,
    hanzi: "西瓜",
    pinyin: "xīguā",
    meaning_vi: "dưa hấu",
    example: "吃西瓜 (chī xīguā) - Ăn dưa hấu.",
  },
  {
    id: 258,
    hanzi: "希望",
    pinyin: "xīwàng",
    meaning_vi: "hy vọng",
    example: "我希望去北京 (wǒ xīwàng qù Běijīng) - Tôi hy vọng đi Bắc Kinh.",
  },
  {
    id: 259,
    hanzi: "洗",
    pinyin: "xǐ",
    meaning_vi: "rửa, giặt",
    example: "洗衣服 (xǐ yīfu) - Giặt quần áo.",
  },
  {
    id: 260,
    hanzi: "小时",
    pinyin: "xiǎoshí",
    meaning_vi: "tiếng đồng hồ",
    example: "两个小时 (liǎng gè xiǎoshí) - 2 tiếng đồng hồ.",
  },
  {
    id: 261,
    hanzi: "笑",
    pinyin: "xiào",
    meaning_vi: "cười",
    example: "别笑了 (bié xiào le) - Đừng cười nữa.",
  },
  {
    id: 262,
    hanzi: "新",
    pinyin: "xīn",
    meaning_vi: "mới",
    example: "新衣服 (xīn yīfu) - Quần áo mới.",
  },
  {
    id: 263,
    hanzi: "姓",
    pinyin: "xìng",
    meaning_vi: "họ (tên)",
    example: "我姓王 (wǒ xìng Wáng) - Tôi họ Vương.",
  },
  {
    id: 264,
    hanzi: "休息",
    pinyin: "xiūxi",
    meaning_vi: "nghỉ ngơi",
    example: "累了就休息 (lèi le jiù xiūxi) - Mệt thì nghỉ ngơi.",
  },
  {
    id: 265,
    hanzi: "雪",
    pinyin: "xuě",
    meaning_vi: "tuyết",
    example: "下雪了 (xià xuě le) - Tuyết rơi rồi.",
  },
  {
    id: 266,
    hanzi: "颜色",
    pinyin: "yánsè",
    meaning_vi: "màu sắc",
    example: "什么颜色？ (shénme yánsè?) - Màu gì thế?",
  },
  {
    id: 267,
    hanzi: "眼睛",
    pinyin: "yǎnjing",
    meaning_vi: "mắt",
    example: "大眼睛 (dà yǎnjing) - Mắt to.",
  },
  {
    id: 268,
    hanzi: "羊肉",
    pinyin: "yángròu",
    meaning_vi: "thịt dê/cừu",
    example: "吃羊肉 (chī yángròu) - Ăn thịt dê.",
  },
  {
    id: 269,
    hanzi: "药",
    pinyin: "yào",
    meaning_vi: "thuốc",
    example: "吃药 (chī yào) - Uống thuốc.",
  },
  {
    id: 270,
    hanzi: "要",
    pinyin: "yào",
    meaning_vi: "muốn, cần, phải",
    example: "我要买书 (wǒ yào mǎi shū) - Tôi muốn mua sách.",
  },
  {
    id: 271,
    hanzi: "也",
    pinyin: "yě",
    meaning_vi: "cũng",
    example: "我也去 (wǒ yě qù) - Tôi cũng đi.",
  },
  {
    id: 272,
    hanzi: "一下",
    pinyin: "yíxià",
    meaning_vi: "một chút, một lát",
    example: "等一下 (děng yíxià) - Đợi một chút.",
  },
  {
    id: 273,
    hanzi: "一起",
    pinyin: "yìqǐ",
    meaning_vi: "cùng nhau",
    example: "一起吃饭 (yìqǐ chī fàn) - Cùng nhau ăn cơm.",
  },
  {
    id: 274,
    hanzi: "已经",
    pinyin: "yǐjīng",
    meaning_vi: "đã, rồi",
    example: "他已经走了 (tā yǐjīng zǒu le) - Anh ấy đã đi rồi.",
  },
  {
    id: 275,
    hanzi: "意思",
    pinyin: "yìsi",
    meaning_vi: "ý nghĩa",
    example: "什么意思？ (shénme yìsi?) - Ý gì thế?",
  },
  {
    id: 276,
    hanzi: "因为",
    pinyin: "yīnwèi",
    meaning_vi: "vì, bởi vì",
    example: "因为很忙 (yīnwèi hěn máng) - Bởi vì rất bận.",
  },
  {
    id: 277,
    hanzi: "所以",
    pinyin: "suǒyǐ",
    meaning_vi: "cho nên",
    example: "所以不去 (suǒyǐ bú qù) - Cho nên không đi.",
  },
  {
    id: 278,
    hanzi: "阴",
    pinyin: "yīn",
    meaning_vi: "âm (trời âm u)",
    example: "阴天 (yīntiān) - Ngày u ám.",
  },
  {
    id: 279,
    hanzi: "游泳",
    pinyin: "yóuyǒng",
    meaning_vi: "bơi lội",
    example: "去游泳 (qù yóuyǒng) - Đi bơi.",
  },
  {
    id: 280,
    hanzi: "右边",
    pinyin: "yòubian",
    meaning_vi: "bên phải",
    example: "往右走 (wǎng yòu zǒu) - Đi về bên phải.",
  },
  {
    id: 281,
    hanzi: "鱼",
    pinyin: "yú",
    meaning_vi: "con cá",
    example: "我不吃鱼 (wǒ bù chī yú) - Tôi không ăn cá.",
  },
  {
    id: 282,
    hanzi: "远",
    pinyin: "yuǎn",
    meaning_vi: "xa",
    example: "离家很远 (lí jiā hěn yuǎn) - Cách nhà rất xa.",
  },
  {
    id: 283,
    hanzi: "运动",
    pinyin: "yùndòng",
    meaning_vi: "vận động, thể thao",
    example: "每天运动 (měitiān yùndòng) - Vận động mỗi ngày.",
  },
  {
    id: 284,
    hanzi: "再",
    pinyin: "zài",
    meaning_vi: "lại (hành động trong tương lai)",
    example: "再见 (zàijiàn) - Tạm biệt (hẹn gặp lại).",
  },
  {
    id: 285,
    hanzi: "早上",
    pinyin: "zǎoshang",
    meaning_vi: "sáng sớm",
    example: "早上六点 (zǎoshang liù diǎn) - 6 giờ sáng.",
  },
  {
    id: 286,
    hanzi: "张",
    pinyin: "zhāng",
    meaning_vi: "tờ, tấm (lượng từ)",
    example: "一张纸 (yì zhāng zhǐ) - Một tờ giấy.",
  },
  {
    id: 287,
    hanzi: "丈夫",
    pinyin: "zhàngfu",
    meaning_vi: "chồng",
    example: "我丈夫是医生 (wǒ zhàngfu shì yīshēng) - Chồng tôi là bác sĩ.",
  },
  {
    id: 288,
    hanzi: "找",
    pinyin: "zhǎo",
    meaning_vi: "tìm",
    example: "找工作 (zhǎo gōngzuò) - Tìm việc làm.",
  },
  {
    id: 289,
    hanzi: "真",
    pinyin: "zhēn",
    meaning_vi: "thật, thực sự",
    example: "真的吗？ (zhēn de ma?) - Thật sao?",
  },
  {
    id: 290,
    hanzi: "正在",
    pinyin: "zhèngzài",
    meaning_vi: "đang",
    example: "正在开会 (zhèngzài kāihuì) - Đang họp.",
  },
  {
    id: 291,
    hanzi: "知道",
    pinyin: "zhīdào",
    meaning_vi: "biết",
    example: "我知道了 (wǒ zhīdào le) - Tôi biết rồi.",
  },
  {
    id: 292,
    hanzi: "准备",
    pinyin: "zhǔnbèi",
    meaning_vi: "chuẩn bị",
    example: "准备好了 (zhǔnbèi hǎo le) - Chuẩn bị xong rồi.",
  },
  {
    id: 293,
    hanzi: "左边",
    pinyin: "zuǒbian",
    meaning_vi: "bên trái",
    example: "往左看 (wǎng zuǒ kàn) - Nhìn sang trái.",
  },
  {
    id: 294,
    hanzi: "走",
    pinyin: "zǒu",
    meaning_vi: "đi",
    example: "我们走吧 (wǒmen zǒu ba) - Chúng ta đi thôi.",
  },
  {
    id: 295,
    hanzi: "最",
    pinyin: "zuì",
    meaning_vi: "nhất",
    example: "最好的朋友 (zuì hǎo de péngyou) - Người bạn tốt nhất.",
  },
  {
    id: 296,
    hanzi: "阿姨",
    pinyin: "āyí",
    meaning_vi: "dì, cô",
    example: "阿姨好 (āyí hǎo) - Chào dì.",
  },
  {
    id: 297,
    hanzi: "啊",
    pinyin: "a",
    meaning_vi: "a, chà (trợ từ)",
    example: "好啊 (hǎo a) - Được thôi.",
  },
  {
    id: 298,
    hanzi: "矮",
    pinyin: "ǎi",
    meaning_vi: "thấp, lùn",
    example: "他不矮 (tā bù ǎi) - Anh ấy không thấp.",
  },
  {
    id: 299,
    hanzi: "安静",
    pinyin: "ānjìng",
    meaning_vi: "yên tĩnh",
    example: "请安静 (qǐng ānjìng) - Xin hãy yên tĩnh.",
  },
  {
    id: 300,
    hanzi: "把",
    pinyin: "bǎ",
    meaning_vi: "đem, nắm (lượng từ/giới từ)",
    example: "把门关上 (bǎ mén guānshàng) - Hãy đóng cửa vào.",
  },
  {
    id: 301,
    hanzi: "搬",
    pinyin: "bān",
    meaning_vi: "dời, chuyển",
    example: "搬家 (bān jiā) - Chuyển nhà.",
  },
  {
    id: 302,
    hanzi: "办法",
    pinyin: "bànfǎ",
    meaning_vi: "biện pháp, cách",
    example: "好办法 (hǎo bànfǎ) - Cách hay.",
  },
  {
    id: 303,
    hanzi: "办公室",
    pinyin: "bàngōngshì",
    meaning_vi: "văn phòng",
    example: "在办公室 (zài bàngōngshì) - Ở văn phòng.",
  },
  {
    id: 304,
    hanzi: "半",
    pinyin: "bàn",
    meaning_vi: "nửa",
    example: "半个小时 (bàn gè xiǎoshí) - Nửa tiếng đồng hồ.",
  },
  {
    id: 305,
    hanzi: "帮忙",
    pinyin: "bāngmáng",
    meaning_vi: "giúp đỡ",
    example: "请帮个忙 (qǐng bāng gè máng) - Xin hãy giúp một tay.",
  },
  {
    id: 306,
    hanzi: "包",
    pinyin: "bāo",
    meaning_vi: "bao, túi",
    example: "面包 (miànbāo) - Bánh mì.",
  },
  {
    id: 307,
    hanzi: "饱",
    pinyin: "bǎo",
    meaning_vi: "no",
    example: "我吃饱了 (wǒ chī bǎo le) - Tôi ăn no rồi.",
  },
  {
    id: 308,
    hanzi: "北方",
    pinyin: "běifāng",
    meaning_vi: "phương bắc",
    example: "北方人 (běifāng rén) - Người phương bắc.",
  },
  {
    id: 309,
    hanzi: "被",
    pinyin: "bèi",
    meaning_vi: "bị, được (câu bị động)",
    example: "被他看见了 (bèi tā kànjiàn le) - Bị anh ấy nhìn thấy rồi.",
  },
  {
    id: 310,
    hanzi: "鼻子",
    pinyin: "bízi",
    meaning_vi: "mũi",
    example: "高鼻子 (gāo bízi) - Mũi cao.",
  },
  {
    id: 311,
    hanzi: "比较",
    pinyin: "bǐjiào",
    meaning_vi: "so sánh, khá là",
    example: "比较好 (bǐjiào hǎo) - Khá là tốt.",
  },
  {
    id: 312,
    hanzi: "比赛",
    pinyin: "bǐsài",
    meaning_vi: "trận đấu, cuộc thi",
    example: "足球比赛 (zúqiú bǐsài) - Trận đấu bóng đá.",
  },
  {
    id: 313,
    hanzi: "笔记本",
    pinyin: "bǐjìběn",
    meaning_vi: "vở ghi chép, laptop",
    example: "笔记本电脑 (bǐjìběn diànnǎo) - Máy tính xách tay.",
  },
  {
    id: 314,
    hanzi: "必须",
    pinyin: "bìxū",
    meaning_vi: "phải, bắt buộc",
    example: "必须去 (bìxū qù) - Phải đi.",
  },
  {
    id: 315,
    hanzi: "变化",
    pinyin: "biànhuà",
    meaning_vi: "biến hóa, thay đổi",
    example: "变化很大 (biànhuà hěn dà) - Thay đổi rất lớn.",
  },
  {
    id: 316,
    hanzi: "表演",
    pinyin: "biǎoyǎn",
    meaning_vi: "biểu diễn",
    example: "精彩的表演 (jīngcǎi de biǎoyǎn) - Buổi biểu diễn đặc sắc.",
  },
  {
    id: 317,
    hanzi: "别人",
    pinyin: "biérén",
    meaning_vi: "người khác",
    example: "别告诉别人 (bié gàosu biérén) - Đừng nói với người khác.",
  },
  {
    id: 318,
    hanzi: "宾馆",
    pinyin: "bīnguǎn",
    meaning_vi: "nhà khách, khách sạn",
    example: "住宾馆 (zhù bīnguǎn) - Ở khách sạn.",
  },
  {
    id: 319,
    hanzi: "冰箱",
    pinyin: "bīngxiāng",
    meaning_vi: "tủ lạnh",
    example: "在冰箱里 (zài bīngxiāng lǐ) - Ở trong tủ lạnh.",
  },
  {
    id: 320,
    hanzi: "不仅",
    pinyin: "bùjǐn",
    meaning_vi: "không những",
    example: "不仅是他 (bùjǐn shì tā) - Không chỉ là anh ấy.",
  },
  {
    id: 321,
    hanzi: "才",
    pinyin: "cái",
    meaning_vi: "mới (muộn)",
    example: "他才来 (tā cái lái) - Anh ấy mới đến.",
  },
  {
    id: 322,
    hanzi: "菜单",
    pinyin: "càidān",
    meaning_vi: "thực đơn",
    example: "请看菜单 (qǐng kàn càidān) - Mời xem thực đơn.",
  },
  {
    id: 323,
    hanzi: "参加",
    pinyin: "cānjiā",
    meaning_vi: "tham gia",
    example: "参加会议 (cānjiā huìyì) - Tham gia cuộc họp.",
  },
  {
    id: 324,
    hanzi: "草",
    pinyin: "cǎo",
    meaning_vi: "cỏ",
    example: "绿草 (lǜ cǎo) - Cỏ xanh.",
  },
  {
    id: 325,
    hanzi: "层",
    pinyin: "céng",
    meaning_vi: "tầng, lớp",
    example: "三层楼 (sān céng lóu) - Nhà ba tầng.",
  },
  {
    id: 326,
    hanzi: "差",
    pinyin: "chà",
    meaning_vi: "kém, thiếu",
    example: "身体很差 (shēntǐ hěn chà) - Sức khỏe rất kém.",
  },
  {
    id: 327,
    hanzi: "超市",
    pinyin: "chāoshì",
    meaning_vi: "siêu thị",
    example: "去超市 (qù chāoshì) - Đi siêu thị.",
  },
  {
    id: 328,
    hanzi: "衬衫",
    pinyin: "chènshān",
    meaning_vi: "áo sơ mi",
    example: "白衬衫 (bái chènshān) - Sơ mi trắng.",
  },
  {
    id: 329,
    hanzi: "成绩",
    pinyin: "chéngjì",
    meaning_vi: "thành tích",
    example: "考试成绩 (kǎoshì chéngjì) - Thành tích thi cử.",
  },
  {
    id: 330,
    hanzi: "城市",
    pinyin: "chéngshì",
    meaning_vi: "thành phố",
    example: "大城市 (dà chéngshì) - Thành phố lớn.",
  },
  {
    id: 331,
    hanzi: "迟到",
    pinyin: "chídào",
    meaning_vi: "đến muộn",
    example: "别迟到 (bié chídào) - Đừng đến muộn.",
  },
  {
    id: 332,
    hanzi: "出现",
    pinyin: "chūxiàn",
    meaning_vi: "xuất hiện",
    example: "出现了问题 (chūxiàn le wèntí) - Xuất hiện vấn đề rồi.",
  },
  {
    id: 333,
    hanzi: "厨房",
    pinyin: "chúfáng",
    meaning_vi: "nhà bếp",
    example: "在厨房做饭 (zài chúfáng zuòfàn) - Nấu cơm trong bếp.",
  },
  {
    id: 334,
    hanzi: "除了",
    pinyin: "chúle",
    meaning_vi: "ngoài ra",
    example: "除了我 (chúle wǒ) - Ngoài tôi ra.",
  },
  {
    id: 335,
    hanzi: "春",
    pinyin: "chūn",
    meaning_vi: "mùa xuân",
    example: "春天来了 (chūntiān lái le) - Mùa xuân đến rồi.",
  },
  {
    id: 336,
    hanzi: "词典",
    pinyin: "cídiǎn",
    meaning_vi: "từ điển",
    example: "查词典 (chá cídiǎn) - Tra từ điển.",
  },
  {
    id: 337,
    hanzi: "聪明",
    pinyin: "cōngmíng",
    meaning_vi: "thông minh",
    example: "聪明的孩子 (cōngmíng de háizi) - Đứa trẻ thông minh.",
  },
  {
    id: 338,
    hanzi: "打扫",
    pinyin: "dǎsǎo",
    meaning_vi: "quét dọn",
    example: "打扫房间 (dǎsǎo fángjiān) - Dọn dẹp phòng.",
  },
  {
    id: 339,
    hanzi: "打算",
    pinyin: "dǎsuàn",
    meaning_vi: "dự định",
    example: "你有什么打算？ (nǐ yǒu shénme dǎsuàn?) - Bạn có dự định gì?",
  },
  {
    id: 340,
    hanzi: "带",
    pinyin: "dài",
    meaning_vi: "mang, đem theo",
    example: "带钱 (dài qián) - Mang theo tiền.",
  },
  {
    id: 341,
    hanzi: "担心",
    pinyin: "dānxīn",
    meaning_vi: "lo lắng",
    example: "别担心 (bié dānxīn) - Đừng lo lắng.",
  },
  {
    id: 342,
    hanzi: "蛋糕",
    pinyin: "dàngāo",
    meaning_vi: "bánh gato, bánh ngọt",
    example: "吃蛋糕 (chī dàngāo) - Ăn bánh ngọt.",
  },
  {
    id: 343,
    hanzi: "当然",
    pinyin: "dāngrán",
    meaning_vi: "đương nhiên",
    example: "当然可以 (dāngrán kěyǐ) - Đương nhiên có thể.",
  },
  {
    id: 344,
    hanzi: "灯",
    pinyin: "dēng",
    meaning_vi: "đèn",
    example: "开灯 (kāi dēng) - Mở đèn.",
  },
  {
    id: 345,
    hanzi: "低",
    pinyin: "dī",
    meaning_vi: "thấp",
    example: "低头 (dī tóu) - Cúi đầu.",
  },
  {
    id: 346,
    hanzi: "地",
    pinyin: "de",
    meaning_vi: "trợ từ (một cách...)",
    example: "高兴地笑了 (gāoxìng de xiào le) - Cười một cách vui vẻ.",
  },
  {
    id: 347,
    hanzi: "地图",
    pinyin: "dìtú",
    meaning_vi: "bản đồ",
    example: "看地图 (kàn dìtú) - Xem bản đồ.",
  },
  {
    id: 348,
    hanzi: "电梯",
    pinyin: "diàntī",
    meaning_vi: "thang máy",
    example: "坐电梯 (zuò diàntī) - Đi thang máy.",
  },
  {
    id: 349,
    hanzi: "电子邮件",
    pinyin: "diànzǐ yóujiàn",
    meaning_vi: "thư điện tử",
    example: "发电子邮件 (fā diànzǐ yóujiàn) - Gửi email.",
  },
  {
    id: 350,
    hanzi: "东",
    pinyin: "dōng",
    meaning_vi: "phương đông",
    example: "向东走 (xiàng dōng zǒu) - Đi về hướng đông.",
  },
  {
    id: 351,
    hanzi: "冬",
    pinyin: "dōng",
    meaning_vi: "mùa đông",
    example: "冬天很冷 (dōngtiān hěn lěng) - Mùa đông rất lạnh.",
  },
  {
    id: 352,
    hanzi: "动物",
    pinyin: "dòngwù",
    meaning_vi: "động vật",
    example: "去动物园 (qù dòngwùyuán) - Đi vườn bách thú.",
  },
  {
    id: 353,
    hanzi: "短",
    pinyin: "duǎn",
    meaning_vi: "ngắn",
    example: "头发很短 (tóufa hěn duǎn) - Tóc rất ngắn.",
  },
  {
    id: 354,
    hanzi: "段",
    pinyin: "duàn",
    meaning_vi: "đoạn, khoảng",
    example: "一段路 (yí duàn lù) - Một đoạn đường.",
  },
  {
    id: 355,
    hanzi: "锻炼",
    pinyin: "duànliàn",
    meaning_vi: "luyện tập, rèn luyện",
    example: "锻炼身体 (duànliàn shēntǐ) - Rèn luyện thân thể.",
  },
  {
    id: 356,
    hanzi: "多么",
    pinyin: "duōme",
    meaning_vi: "biết bao, dường nào",
    example: "多么漂亮啊！ (duōme piàoliang a!) - Đẹp biết bao!",
  },
  {
    id: 357,
    hanzi: "饿",
    pinyin: "è",
    meaning_vi: "đói",
    example: "我饿了 (wǒ è le) - Tôi đói rồi.",
  },
  {
    id: 358,
    hanzi: "耳环",
    pinyin: "ěrhuán",
    meaning_vi: "bông tai",
    example: "戴耳环 (dài ěrhuán) - Đeo bông tai.",
  },
  {
    id: 359,
    hanzi: "发",
    pinyin: "fā",
    meaning_vi: "gửi, phát",
    example: "发短信 (fā duǎnxìn) - Gửi tin nhắn.",
  },
  {
    id: 360,
    hanzi: "发烧",
    pinyin: "fāshāo",
    meaning_vi: "sốt",
    example: "他发烧了 (tā fāshāo le) - Anh ấy bị sốt rồi.",
  },
  {
    id: 361,
    hanzi: "发现",
    pinyin: "fāxiàn",
    meaning_vi: "phát hiện",
    example:
      "我发现了一个秘密 (wǒ fāxiàn le yí gè mìmì) - Tôi phát hiện một bí mật.",
  },
  {
    id: 362,
    hanzi: "方便",
    pinyin: "fāngbiàn",
    meaning_vi: "thuận tiện",
    example: "很方便 (hěn fāngbiàn) - Rất thuận tiện.",
  },
  {
    id: 363,
    hanzi: "放心",
    pinyin: "fàngxīn",
    meaning_vi: "yên tâm",
    example: "请放心 (qǐng fàngxīn) - Xin hãy yên tâm.",
  },
  {
    id: 364,
    hanzi: "分",
    pinyin: "fēn",
    meaning_vi: "phút, điểm",
    example: "八分 (bā fēn) - 8 phút / 8 điểm.",
  },
  {
    id: 365,
    hanzi: "附近",
    pinyin: "fùjìn",
    meaning_vi: "lân cận, gần đây",
    example: "学校附近 (xuéxiào fùjìn) - Gần trường học.",
  },
  {
    id: 366,
    hanzi: "复习",
    pinyin: "fùxí",
    meaning_vi: "ôn tập",
    example: "复习课文 (fùxí kèwén) - Ôn tập bài khóa.",
  },
  {
    id: 367,
    hanzi: "干净",
    pinyin: "gānjìng",
    meaning_vi: "sạch sẽ",
    example: "打扫干净 (dǎsǎo gānjìng) - Dọn dẹp sạch sẽ.",
  },
  {
    id: 368,
    hanzi: "敢",
    pinyin: "gǎn",
    meaning_vi: "dám",
    example: "你敢吗？ (nǐ gǎn ma?) - Bạn dám không?",
  },
  {
    id: 369,
    hanzi: "感冒",
    pinyin: "gǎnmào",
    meaning_vi: "cảm mạo, cảm lạnh",
    example: "我感冒了 (wǒ gǎnmào le) - Tôi bị cảm rồi.",
  },
  {
    id: 370,
    hanzi: "刚才",
    pinyin: "gāngcái",
    meaning_vi: "vừa mới",
    example: "刚才谁来了？ (gāngcái shéi lái le?) - Vừa nãy ai đến thế?",
  },
  {
    id: 371,
    hanzi: "跟",
    pinyin: "gēn",
    meaning_vi: "với, theo",
    example: "跟我走 (gēn wǒ zǒu) - Đi theo tôi.",
  },
  {
    id: 372,
    hanzi: "根据",
    pinyin: "gēnjù",
    meaning_vi: "căn cứ vào",
    example:
      "根据课文内容 (gēnjù kèwén nèiróng) - Căn cứ vào nội dung bài học.",
  },
  {
    id: 373,
    hanzi: "更",
    pinyin: "gèng",
    meaning_vi: "hơn nữa, thêm",
    example: "更好 (gèng hǎo) - Tốt hơn.",
  },
  {
    id: 374,
    hanzi: "公园",
    pinyin: "gōngyuán",
    meaning_vi: "công viên",
    example: "去公园玩 (qù gōngyuán wán) - Đi công viên chơi.",
  },
  {
    id: 375,
    hanzi: "故事",
    pinyin: "gùshì",
    meaning_vi: "câu chuyện",
    example: "讲故事 (jiǎng gùshì) - Kể chuyện.",
  },
  {
    id: 376,
    hanzi: "刮风",
    pinyin: "guāfēng",
    meaning_vi: "nổi gió",
    example: "外面刮风了 (wàimiàn guāfēng le) - Bên ngoài nổi gió rồi.",
  },
  {
    id: 377,
    hanzi: "关",
    pinyin: "guān",
    meaning_vi: "đóng, tắt",
    example: "关灯 (guān dēng) - Tắt đèn.",
  },
  {
    id: 378,
    hanzi: "关系",
    pinyin: "guānxì",
    meaning_vi: "quan hệ",
    example: "没关系 (méiguānxì) - Không có gì/Không sao.",
  },
  {
    id: 379,
    hanzi: "关心",
    pinyin: "guānxīn",
    meaning_vi: "quan tâm",
    example: "多关心身体 (duō guānxīn shēntǐ) - Quan tâm sức khỏe nhiều hơn.",
  },
  {
    id: 380,
    hanzi: "关于",
    pinyin: "guānyú",
    meaning_vi: "về, liên quan đến",
    example: "关于学习 (guānyú xuéxí) - Về việc học tập.",
  },
  {
    id: 381,
    hanzi: "国家",
    pinyin: "guójiā",
    meaning_vi: "quốc gia, đất nước",
    example: "不同的国家 (bùtóng de guójiā) - Các quốc gia khác nhau.",
  },
  {
    id: 382,
    hanzi: "果汁",
    pinyin: "guǒzhī",
    meaning_vi: "nước ép trái cây",
    example: "喝果汁 (hē guǒzhī) - Uống nước ép.",
  },
  {
    id: 383,
    hanzi: "过去",
    pinyin: "guòqù",
    meaning_vi: "quá khứ, đi qua",
    example: "过去的事情 (guòqù de shìqing) - Chuyện đã qua.",
  },
  {
    id: 384,
    hanzi: "害怕",
    pinyin: "hàipà",
    meaning_vi: "sợ hãi",
    example: "别害怕 (bié hàipà) - Đừng sợ.",
  },
  {
    id: 385,
    hanzi: "河",
    pinyin: "hé",
    meaning_vi: "sông",
    example: "小河 (xiǎohé) - Con sông nhỏ.",
  },
  {
    id: 386,
    hanzi: "黑板",
    pinyin: "hēibǎn",
    meaning_vi: "bảng đen",
    example: "看黑板 (kàn hēibǎn) - Nhìn lên bảng.",
  },
  {
    id: 387,
    hanzi: "护照",
    pinyin: "hùzhào",
    meaning_vi: "hộ chiếu",
    example: "办护照 (bàn hùzhào) - Làm hộ chiếu.",
  },
  {
    id: 388,
    hanzi: "花",
    pinyin: "huā",
    meaning_vi: "hoa, tiêu (tiền/thời gian)",
    example: "花钱 (huā qián) - Tiêu tiền.",
  },
  {
    id: 389,
    hanzi: "花园",
    pinyin: "huāyuán",
    meaning_vi: "vườn hoa",
    example: "漂亮的花园 (piàoliang de huāyuán) - Vườn hoa đẹp.",
  },
  {
    id: 390,
    hanzi: "画",
    pinyin: "huà",
    meaning_vi: "vẽ, bức tranh",
    example: "画画 (huà huà) - Vẽ tranh.",
  },
  {
    id: 391,
    hanzi: "坏",
    pinyin: "huài",
    meaning_vi: "hỏng, xấu",
    example: "坏了 (huài le) - Hỏng rồi.",
  },
  {
    id: 392,
    hanzi: "还",
    pinyin: "huán",
    meaning_vi: "trả lại",
    example: "还书 (huán shū) - Trả sách.",
  },
  {
    id: 393,
    hanzi: "环境",
    pinyin: "huánjìng",
    meaning_vi: "môi trường",
    example: "环境优美 (huánjìng yōuměi) - Môi trường ưu mỹ.",
  },
  {
    id: 394,
    hanzi: "换",
    pinyin: "huàn",
    meaning_vi: "thay đổi, đổi",
    example: "换钱 (huàn qián) - Đổi tiền.",
  },
  {
    id: 395,
    hanzi: "黄河",
    pinyin: "Huáng Hé",
    meaning_vi: "Hoàng Hà",
    example: "黄河很大 (Huáng Hé hěn dà) - Sông Hoàng Hà rất lớn.",
  },
  {
    id: 396,
    hanzi: "会议",
    pinyin: "huìyì",
    meaning_vi: "hội nghị, cuộc họp",
    example: "开会 (kāi huì) - Họp.",
  },
  {
    id: 397,
    hanzi: "或者",
    pinyin: "huòzhě",
    meaning_vi: "hoặc là (trong câu trần thuật)",
    example: "你或者他 (nǐ huòzhě tā) - Bạn hoặc là anh ấy.",
  },
  {
    id: 398,
    hanzi: "几乎",
    pinyin: "jīhū",
    meaning_vi: "hầu như",
    example: "几乎忘了 (jīhū wàng le) - Hầu như quên mất rồi.",
  },
  {
    id: 399,
    hanzi: "机会",
    pinyin: "jīhuì",
    meaning_vi: "cơ hội",
    example: "好机会 (hǎo jīhuì) - Cơ hội tốt.",
  },
  {
    id: 400,
    hanzi: "极",
    pinyin: "jí",
    meaning_vi: "cực kỳ",
    example: "好极了 (hǎo jí le) - Tốt cực kỳ.",
  },
  {
    id: 401,
    hanzi: "记得",
    pinyin: "jìde",
    meaning_vi: "nhớ, ghi nhớ",
    example: "我还记得你 (Wǒ hái jìde nǐ) - Tôi vẫn còn nhớ bạn.",
  },
  {
    id: 402,
    hanzi: "季节",
    pinyin: "jìjié",
    meaning_vi: "mùa, thời vụ",
    example: "喜欢的季节 (xǐhuan de jìjié) - Mùa yêu thích.",
  },
  {
    id: 403,
    hanzi: "检查",
    pinyin: "jiǎnchá",
    meaning_vi: "kiểm tra",
    example: "检查身体 (jiǎnchá shēntǐ) - Kiểm tra sức khỏe.",
  },
  {
    id: 404,
    hanzi: "简单",
    pinyin: "jiǎndān",
    meaning_vi: "đơn giản",
    example: "这道题很简单 (Zhè dào tí hěn jiǎndān) - Câu này rất đơn giản.",
  },
  {
    id: 405,
    hanzi: "见面",
    pinyin: "jiànmiàn",
    meaning_vi: "gặp mặt",
    example: "跟他见面 (Gēn tā jiànmiàn) - Gặp mặt anh ấy.",
  },
  {
    id: 406,
    hanzi: "健康",
    pinyin: "jiànkāng",
    meaning_vi: "khỏe mạnh",
    example: "祝你健康 (Zhù nǐ jiànkāng) - Chúc bạn khỏe mạnh.",
  },
  {
    id: 407,
    hanzi: "讲",
    pinyin: "jiǎng",
    meaning_vi: "nói, kể, giảng",
    example: "讲故事 (jiǎng gùshì) - Kể chuyện.",
  },
  {
    id: 408,
    hanzi: "教",
    pinyin: "jiāo",
    meaning_vi: "dạy dỗ",
    example: "教汉语 (jiāo Hànyǔ) - Dạy tiếng Trung.",
  },
  {
    id: 409,
    hanzi: "脚",
    pinyin: "jiǎo",
    meaning_vi: "chân",
    example: "我的脚疼 (Wǒ de jiǎo téng) - Chân tôi bị đau.",
  },
  {
    id: 410,
    hanzi: "角",
    pinyin: "jiǎo",
    meaning_vi: "góc, hào (tiền)",
    example: "一角钱 (yì jiǎo qián) - Một hào.",
  },
  {
    id: 411,
    hanzi: "接",
    pinyin: "jiē",
    meaning_vi: "đón, nhận",
    example: "去机场接人 (qù jīchǎng jiē rén) - Đi sân bay đón người.",
  },
  {
    id: 412,
    hanzi: "街道",
    pinyin: "jiēdào",
    meaning_vi: "phố, đường phố",
    example: "干净的街道 (gānjìng de jiēdào) - Đường phố sạch sẽ.",
  },
  {
    id: 413,
    hanzi: "结婚",
    pinyin: "jiéhūn",
    meaning_vi: "kết hôn",
    example: "他们结婚了 (Tāmen jiéhūn le) - Họ kết hôn rồi.",
  },
  {
    id: 414,
    hanzi: "结束",
    pinyin: "jiéshù",
    meaning_vi: "kết thúc",
    example: "会议结束了 (Huìyì jiéshù le) - Cuộc họp kết thúc rồi.",
  },
  {
    id: 415,
    hanzi: "节目",
    pinyin: "jiémù",
    meaning_vi: "tiết mục, chương trình",
    example: "看电视节目 (kàn diànshì jiémù) - Xem chương trình TV.",
  },
  {
    id: 416,
    hanzi: "节日",
    pinyin: "jiérì",
    meaning_vi: "ngày lễ",
    example: "祝你节日快乐 (Zhù nǐ jiérì kuàilè) - Chúc bạn ngày lễ vui vẻ.",
  },
  {
    id: 417,
    hanzi: "解决",
    pinyin: "jiějué",
    meaning_vi: "giải quyết",
    example: "解决问题 (jiějué wèntí) - Giải quyết vấn đề.",
  },
  {
    id: 418,
    hanzi: "借",
    pinyin: "jiè",
    meaning_vi: "mượn, vay",
    example: "借书 (jiè shū) - Mượn sách.",
  },
  {
    id: 419,
    hanzi: "经常",
    pinyin: "jīngcháng",
    meaning_vi: "thường xuyên",
    example: "经常运动 (jīngcháng yùndòng) - Thường xuyên vận động.",
  },
  {
    id: 420,
    hanzi: "经过",
    pinyin: "jīngguò",
    meaning_vi: "trải qua, đi ngang qua",
    example: "经过超市 (jīngguò chāoshì) - Đi ngang qua siêu thị.",
  },
  {
    id: 421,
    hanzi: "经理",
    pinyin: "jīnglǐ",
    meaning_vi: "giám đốc, quản lý",
    example: "王经理 (Wáng jīnglǐ) - Quản lý Vương.",
  },
  {
    id: 422,
    hanzi: "久",
    pinyin: "jiǔ",
    meaning_vi: "lâu",
    example: "等了很久 (děng le hěn jiǔ) - Đợi rất lâu rồi.",
  },
  {
    id: 423,
    hanzi: "旧",
    pinyin: "jiù",
    meaning_vi: "cũ",
    example: "旧衣服 (jiù yīfu) - Quần áo cũ.",
  },
  {
    id: 424,
    hanzi: "句子",
    pinyin: "jùzi",
    meaning_vi: "câu",
    example: "写句子 (xiě jùzi) - Viết câu.",
  },
  {
    id: 425,
    hanzi: "决定",
    pinyin: "juédìng",
    meaning_vi: "quyết định",
    example: "我不决定 (wǒ bù juédìng) - Tôi không quyết định.",
  },
  {
    id: 426,
    hanzi: "可爱",
    pinyin: "kě'ài",
    meaning_vi: "đáng yêu",
    example: "可爱的猫 (kě'ài de māo) - Con mèo đáng yêu.",
  },
  {
    id: 427,
    hanzi: "渴",
    pinyin: "kě",
    meaning_vi: "khát",
    example: "我渴了 (wǒ kě le) - Tôi khát rồi.",
  },
  {
    id: 428,
    hanzi: "刻",
    pinyin: "kè",
    meaning_vi: "khắc (15 phút)",
    example: "三点一刻 (sān diǎn yí kè) - 3 giờ 15 phút.",
  },
  {
    id: 429,
    hanzi: "客人",
    pinyin: "kèrén",
    meaning_vi: "khách",
    example: "家里有客人 (jiā lǐ yǒu kèrén) - Nhà có khách.",
  },
  {
    id: 430,
    hanzi: "空调",
    pinyin: "kōngtiáo",
    meaning_vi: "máy điều hòa",
    example: "开空调 (kāi kōngtiáo) - Mở điều hòa.",
  },
  {
    id: 431,
    hanzi: "口",
    pinyin: "kǒu",
    meaning_vi: "miệng, lượng từ người",
    example: "一家四口人 (yì jiā sì kǒu rén) - Nhà có 4 người.",
  },
  {
    id: 432,
    hanzi: "哭",
    pinyin: "kū",
    meaning_vi: "khóc",
    example: "别哭了 (bié kū le) - Đừng khóc nữa.",
  },
  {
    id: 433,
    hanzi: "裤子",
    pinyin: "kùzi",
    meaning_vi: "quần",
    example: "买裤子 (mǎi kùzi) - Mua quần.",
  },
  {
    id: 434,
    hanzi: "筷子",
    pinyin: "kuàizi",
    meaning_vi: "đũa",
    example: "用筷子 (yòng kuàizi) - Dùng đũa.",
  },
  {
    id: 435,
    hanzi: "蓝",
    pinyin: "lán",
    meaning_vi: "xanh lam",
    example: "蓝色的天 (lánsè de tiān) - Bầu trời xanh.",
  },
  {
    id: 436,
    hanzi: "老",
    pinyin: "lǎo",
    meaning_vi: "già, cũ",
    example: "老朋友 (lǎo péngyou) - Bạn cũ.",
  },
  {
    id: 437,
    hanzi: "离开",
    pinyin: "líkāi",
    meaning_vi: "rời khỏi",
    example: "离开北京 (líkāi Běijīng) - Rời khỏi Bắc Kinh.",
  },
  {
    id: 438,
    hanzi: "礼物",
    pinyin: "lǐwù",
    meaning_vi: "quà tặng",
    example: "送礼物 (sòng lǐwù) - Tặng quà.",
  },
  {
    id: 439,
    hanzi: "历史",
    pinyin: "lìshǐ",
    meaning_vi: "lịch sử",
    example: "中国历史 (Zhōngguó lìshǐ) - Lịch sử Trung Quốc.",
  },
  {
    id: 440,
    hanzi: "脸",
    pinyin: "liǎn",
    meaning_vi: "mặt",
    example: "洗脸 (xǐ liǎn) - Rửa mặt.",
  },
  {
    id: 441,
    hanzi: "练习",
    pinyin: "liànxí",
    meaning_vi: "luyện tập",
    example: "做练习 (zuò liànxí) - Làm bài tập.",
  },
  {
    id: 442,
    hanzi: "辆",
    pinyin: "liàng",
    meaning_vi: "chiếc (lượng từ xe)",
    example: "一辆自行车 (yí liàng zìxíngchē) - Một chiếc xe đạp.",
  },
  {
    id: 443,
    hanzi: "聊天",
    pinyin: "liáotiān",
    meaning_vi: "tán gẫu",
    example: "跟朋友聊天 (gēn péngyou liáotiān) - Tán gẫu với bạn.",
  },
  {
    id: 444,
    hanzi: "了解",
    pinyin: "liǎojiě",
    meaning_vi: "hiểu rõ",
    example: "我很了解他 (wǒ hěn liǎojiě tā) - Tôi rất hiểu anh ấy.",
  },
  {
    id: 445,
    hanzi: "邻居",
    pinyin: "línjū",
    meaning_vi: "hàng xóm",
    example: "好的邻居 (hǎo de línjū) - Hàng xóm tốt.",
  },
  {
    id: 446,
    hanzi: "留学",
    pinyin: "liúxué",
    meaning_vi: "du học",
    example: "去中国留学 (qù Zhōngguó liúxué) - Đi Trung Quốc du học.",
  },
  {
    id: 447,
    hanzi: "楼",
    pinyin: "lóu",
    meaning_vi: "tòa nhà, tầng",
    example: "上楼 (shàng lóu) - Lên lầu.",
  },
  {
    id: 448,
    hanzi: "绿",
    pinyin: "lǜ",
    meaning_vi: "xanh lá cây",
    example: "绿草 (lǜ cǎo) - Cỏ xanh.",
  },
  {
    id: 449,
    hanzi: "马",
    pinyin: "mǎ",
    meaning_vi: "con ngựa",
    example: "骑马 (qí mǎ) - Cưỡi ngựa.",
  },
  {
    id: 450,
    hanzi: "马上",
    pinyin: "mǎshàng",
    meaning_vi: "ngay lập tức",
    example: "马上就来 (mǎshàng jiù lái) - Đến ngay đây.",
  },
  {
    id: 451,
    hanzi: "满意",
    pinyin: "mǎnyì",
    meaning_vi: "hài lòng",
    example: "我很满意 (Wǒ hěn mǎnyì) - Tôi rất hài lòng.",
  },
  {
    id: 452,
    hanzi: "帽子",
    pinyin: "màozi",
    meaning_vi: "mũ, nón",
    example: "戴帽子 (dài màozi) - Đội mũ.",
  },
  {
    id: 453,
    hanzi: "米",
    pinyin: "mǐ",
    meaning_vi: "mét, gạo",
    example: "一百米 (yìbǎi mǐ) - Một trăm mét.",
  },
  {
    id: 454,
    hanzi: "面包",
    pinyin: "miànbāo",
    meaning_vi: "bánh mì",
    example: "吃面包 (chī miànbāo) - Ăn bánh mì.",
  },
  {
    id: 455,
    hanzi: "面条",
    pinyin: "miàntiáo",
    meaning_vi: "mì sợi",
    example: "做面条 (zuò miàntiáo) - Làm mì.",
  },
  {
    id: 456,
    hanzi: "明白",
    pinyin: "míngbai",
    meaning_vi: "hiểu, rõ ràng",
    example: "我不明白 (Wǒ bù míngbai) - Tôi không hiểu.",
  },
  {
    id: 457,
    hanzi: "拿",
    pinyin: "ná",
    meaning_vi: "cầm, nắm, lấy",
    example: "拿书 (ná shū) - Lấy sách.",
  },
  {
    id: 458,
    hanzi: "奶奶",
    pinyin: "nǎinai",
    meaning_vi: "bà nội",
    example: "奶奶家 (nǎinai jiā) - Nhà bà nội.",
  },
  {
    id: 459,
    hanzi: "南",
    pinyin: "nán",
    meaning_vi: "phương nam",
    example: "越南 (Yuènán) - Việt Nam.",
  },
  {
    id: 460,
    hanzi: "难",
    pinyin: "nán",
    meaning_vi: "khó",
    example: "很难学 (hěn nán xué) - Rất khó học.",
  },
  {
    id: 461,
    hanzi: "难过",
    pinyin: "nánguò",
    meaning_vi: "buồn bã, khó xử",
    example: "我很难过 (wǒ hěn nánguò) - Tôi rất buồn.",
  },
  {
    id: 462,
    hanzi: "年级",
    pinyin: "niánjí",
    meaning_vi: "năm học, lớp (trình độ)",
    example: "三年级 (sān niánjí) - Lớp 3 / Năm thứ 3.",
  },
  {
    id: 463,
    hanzi: "年轻",
    pinyin: "niánqīng",
    meaning_vi: "trẻ tuổi",
    example: "很年轻 (hěn niánqīng) - Rất trẻ.",
  },
  {
    id: 464,
    hanzi: "鸟",
    pinyin: "niǎo",
    meaning_vi: "con chim",
    example: "小鸟 (xiǎoniǎo) - Con chim nhỏ.",
  },
  {
    id: 465,
    hanzi: "努力",
    pinyin: "nǔlì",
    meaning_vi: "nỗ lực, cố gắng",
    example: "努力学习 (nǔlì xuéxí) - Cố gắng học tập.",
  },
  {
    id: 466,
    hanzi: "爬山",
    pinyin: "páshān",
    meaning_vi: "leo núi",
    example: "去爬山 (qù páshān) - Đi leo núi.",
  },
  {
    id: 467,
    hanzi: "盘子",
    pinyin: "pánzi",
    meaning_vi: "cái đĩa",
    example: "洗盘子 (xǐ pánzi) - Rửa đĩa.",
  },
  {
    id: 468,
    hanzi: "胖",
    pinyin: "pàng",
    meaning_vi: "béo, mập",
    example: "他胖了 (tā pàng le) - Anh ấy béo lên rồi.",
  },
  {
    id: 469,
    hanzi: "啤酒",
    pinyin: "píjiǔ",
    meaning_vi: "bia",
    example: "喝啤酒 (hē píjiǔ) - Uống bia.",
  },
  {
    id: 470,
    hanzi: "葡萄",
    pinyin: "pútáo",
    meaning_vi: "nho",
    example: "买葡萄 (mǎi pútáo) - Mua nho.",
  },
  {
    id: 471,
    hanzi: "普通话",
    pinyin: "pǔtōnghuà",
    meaning_vi: "tiếng phổ thông",
    example: "说普通话 (shuō pǔtōnghuà) - Nói tiếng phổ thông.",
  },
  {
    id: 472,
    hanzi: "其实",
    pinyin: "qíshí",
    meaning_vi: "thực ra",
    example: "其实我不去 (qíshí wǒ bú qù) - Thực ra tôi không đi.",
  },
  {
    id: 473,
    hanzi: "其他",
    pinyin: "qítā",
    meaning_vi: "cái khác",
    example: "其他学生 (qítā xuésheng) - Những học sinh khác.",
  },
  {
    id: 474,
    hanzi: "骑",
    pinyin: "qí",
    meaning_vi: "cưỡi, đi (xe đạp/máy)",
    example: "骑自行车 (qí zìxíngchē) - Đi xe đạp.",
  },
  {
    id: 475,
    hanzi: "奇怪",
    pinyin: "qíguài",
    meaning_vi: "kỳ lạ",
    example: "很奇怪 (hěn qíguài) - Rất kỳ lạ.",
  },
  {
    id: 476,
    hanzi: "铅笔",
    pinyin: "qiānbǐ",
    meaning_vi: "bút chì",
    example: "用铅笔 (yòng qiānbǐ) - Dùng bút chì.",
  },
  {
    id: 477,
    hanzi: "清楚",
    pinyin: "qīngchu",
    meaning_vi: "rõ ràng",
    example: "看清楚 (kàn qīngchu) - Nhìn rõ ràng.",
  },
  {
    id: 478,
    hanzi: "秋",
    pinyin: "qiū",
    meaning_vi: "mùa thu",
    example: "秋天到了 (qiūtiān dào le) - Mùa thu đến rồi.",
  },
  {
    id: 479,
    hanzi: "裙子",
    pinyin: "qúnzi",
    meaning_vi: "váy",
    example: "穿裙子 (chuān qúnzi) - Mặc váy.",
  },
  {
    id: 480,
    hanzi: "然后",
    pinyin: "ránhòu",
    meaning_vi: "sau đó",
    example: "然后去吃饭 (ránhòu qù chī fàn) - Sau đó đi ăn cơm.",
  },
  {
    id: 481,
    hanzi: "热情",
    pinyin: "rèqíng",
    meaning_vi: "nhiệt tình",
    example: "热情的邻居 (rèqíng de línjū) - Hàng xóm nhiệt tình.",
  },
  {
    id: 482,
    hanzi: "认为",
    pinyin: "rènwéi",
    meaning_vi: "cho rằng",
    example: "我认为 (wǒ rènwéi) - Tôi cho rằng.",
  },
  {
    id: 483,
    hanzi: "认真",
    pinyin: "rènzhēn",
    meaning_vi: "nghiêm túc, chăm chỉ",
    example: "认真工作 (rènzhēn gōngzuò) - Làm việc nghiêm túc.",
  },
  {
    id: 484,
    hanzi: "容易",
    pinyin: "róngyì",
    meaning_vi: "dễ dàng",
    example: "不容易 (bù róngyì) - Không dễ dàng.",
  },
  {
    id: 485,
    hanzi: "如果",
    pinyin: "rúguǒ",
    meaning_vi: "nếu",
    example: "如果你去 (rúguǒ nǐ qù) - Nếu bạn đi.",
  },
  {
    id: 486,
    hanzi: "伞",
    pinyin: "sǎn",
    meaning_vi: "ô, dù",
    example: "带伞 (dài sǎn) - Mang ô.",
  },
  {
    id: 487,
    hanzi: "上网",
    pinyin: "shàngwǎng",
    meaning_vi: "lên mạng",
    example: "在家上网 (zài jiā shàngwǎng) - Lên mạng ở nhà.",
  },
  {
    id: 488,
    hanzi: "声音",
    pinyin: "shēngyīn",
    meaning_vi: "âm thanh",
    example: "好听的声音 (hǎotīng de shēngyīn) - Giọng nói hay.",
  },
  {
    id: 489,
    hanzi: "世界",
    pinyin: "shìjiè",
    meaning_vi: "thế giới",
    example: "全世界 (quán shìjiè) - Toàn thế giới.",
  },
  {
    id: 490,
    hanzi: "试",
    pinyin: "shì",
    meaning_vi: "thử",
    example: "试衣服 (shì yīfu) - Thử quần áo.",
  },
  {
    id: 491,
    hanzi: "瘦",
    pinyin: "shòu",
    meaning_vi: "gầy, chật",
    example: "他很瘦 (tā hěn shòu) - Anh ấy rất gầy.",
  },
  {
    id: 492,
    hanzi: "舒服",
    pinyin: "shūfu",
    meaning_vi: "thoải mái, dễ chịu",
    example: "身体不舒服 (shēntǐ bù shūfu) - Cơ thể không khỏe.",
  },
  {
    id: 493,
    hanzi: "树",
    pinyin: "shù",
    meaning_vi: "cây",
    example: "大树 (dà shù) - Cây lớn.",
  },
  {
    id: 494,
    hanzi: "数学",
    pinyin: "shùxué",
    meaning_vi: "toán học",
    example: "数学老师 (shùxué lǎoshī) - Giáo viên toán.",
  },
  {
    id: 495,
    hanzi: "刷牙",
    pinyin: "shuāyá",
    meaning_vi: "đánh răng",
    example: "每天刷牙 (měitiān shuāyá) - Đánh răng mỗi ngày.",
  },
  {
    id: 496,
    hanzi: "双",
    pinyin: "shuāng",
    meaning_vi: "đôi (lượng từ)",
    example: "一双鞋 (yì shuāng xié) - Một đôi giày.",
  },
  {
    id: 497,
    hanzi: "水平",
    pinyin: "shuǐpíng",
    meaning_vi: "trình độ",
    example: "汉语水平 (Hànyǔ shuǐpíng) - Trình độ tiếng Trung.",
  },
  {
    id: 498,
    hanzi: "司机",
    pinyin: "sījī",
    meaning_vi: "tài xế",
    example: "出租车司机 (chūzūchē sījī) - Tài xế taxi.",
  },
  {
    id: 499,
    hanzi: "虽然",
    pinyin: "suīrán",
    meaning_vi: "tuy rằng",
    example: "虽然很累 (suīrán hěn lèi) - Tuy rất mệt.",
  },
  {
    id: 500,
    hanzi: "总是",
    pinyin: "zǒngshì",
    meaning_vi: "luôn luôn",
    example: "他总是笑 (tā zǒngshì xiào) - Anh ấy luôn cười.",
  },
];
